//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms3pl.WpfClient.ExDataServices.S03WcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="F0020", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.F00")]
    [System.SerializableAttribute()]
    public partial class F0020 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime CRT_DATEk__BackingFieldField;
        
        private string CRT_NAMEk__BackingFieldField;
        
        private string CRT_STAFFk__BackingFieldField;
        
        private string MSG_CONTENTk__BackingFieldField;
        
        private string MSG_LEVELk__BackingFieldField;
        
        private string MSG_NOk__BackingFieldField;
        
        private string MSG_SUBJECTk__BackingFieldField;
        
        private System.Nullable<System.DateTime> UPD_DATEk__BackingFieldField;
        
        private string UPD_NAMEk__BackingFieldField;
        
        private string UPD_STAFFk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CRT_DATE>k__BackingField", IsRequired=true)]
        public System.DateTime CRT_DATEk__BackingField {
            get {
                return this.CRT_DATEk__BackingFieldField;
            }
            set {
                if ((this.CRT_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.CRT_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("CRT_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CRT_NAME>k__BackingField", IsRequired=true)]
        public string CRT_NAMEk__BackingField {
            get {
                return this.CRT_NAMEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CRT_NAMEk__BackingFieldField, value) != true)) {
                    this.CRT_NAMEk__BackingFieldField = value;
                    this.RaisePropertyChanged("CRT_NAMEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CRT_STAFF>k__BackingField", IsRequired=true)]
        public string CRT_STAFFk__BackingField {
            get {
                return this.CRT_STAFFk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CRT_STAFFk__BackingFieldField, value) != true)) {
                    this.CRT_STAFFk__BackingFieldField = value;
                    this.RaisePropertyChanged("CRT_STAFFk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MSG_CONTENT>k__BackingField", IsRequired=true)]
        public string MSG_CONTENTk__BackingField {
            get {
                return this.MSG_CONTENTk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.MSG_CONTENTk__BackingFieldField, value) != true)) {
                    this.MSG_CONTENTk__BackingFieldField = value;
                    this.RaisePropertyChanged("MSG_CONTENTk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MSG_LEVEL>k__BackingField", IsRequired=true)]
        public string MSG_LEVELk__BackingField {
            get {
                return this.MSG_LEVELk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.MSG_LEVELk__BackingFieldField, value) != true)) {
                    this.MSG_LEVELk__BackingFieldField = value;
                    this.RaisePropertyChanged("MSG_LEVELk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MSG_NO>k__BackingField", IsRequired=true)]
        public string MSG_NOk__BackingField {
            get {
                return this.MSG_NOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.MSG_NOk__BackingFieldField, value) != true)) {
                    this.MSG_NOk__BackingFieldField = value;
                    this.RaisePropertyChanged("MSG_NOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MSG_SUBJECT>k__BackingField", IsRequired=true)]
        public string MSG_SUBJECTk__BackingField {
            get {
                return this.MSG_SUBJECTk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.MSG_SUBJECTk__BackingFieldField, value) != true)) {
                    this.MSG_SUBJECTk__BackingFieldField = value;
                    this.RaisePropertyChanged("MSG_SUBJECTk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UPD_DATE>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> UPD_DATEk__BackingField {
            get {
                return this.UPD_DATEk__BackingFieldField;
            }
            set {
                if ((this.UPD_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.UPD_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("UPD_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UPD_NAME>k__BackingField", IsRequired=true)]
        public string UPD_NAMEk__BackingField {
            get {
                return this.UPD_NAMEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UPD_NAMEk__BackingFieldField, value) != true)) {
                    this.UPD_NAMEk__BackingFieldField = value;
                    this.RaisePropertyChanged("UPD_NAMEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UPD_STAFF>k__BackingField", IsRequired=true)]
        public string UPD_STAFFk__BackingField {
            get {
                return this.UPD_STAFFk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UPD_STAFFk__BackingFieldField, value) != true)) {
                    this.UPD_STAFFk__BackingFieldField = value;
                    this.RaisePropertyChanged("UPD_STAFFk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderIsProblem", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class OrderIsProblem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CREATE_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUST_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUST_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DC_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DC_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUP_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUP_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ROWNUMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TYPEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CREATE_DATE {
            get {
                return this.CREATE_DATEField;
            }
            set {
                if ((this.CREATE_DATEField.Equals(value) != true)) {
                    this.CREATE_DATEField = value;
                    this.RaisePropertyChanged("CREATE_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUST_CODE {
            get {
                return this.CUST_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_CODEField, value) != true)) {
                    this.CUST_CODEField = value;
                    this.RaisePropertyChanged("CUST_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUST_NAME {
            get {
                return this.CUST_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_NAMEField, value) != true)) {
                    this.CUST_NAMEField = value;
                    this.RaisePropertyChanged("CUST_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DC_CODE {
            get {
                return this.DC_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.DC_CODEField, value) != true)) {
                    this.DC_CODEField = value;
                    this.RaisePropertyChanged("DC_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DC_NAME {
            get {
                return this.DC_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.DC_NAMEField, value) != true)) {
                    this.DC_NAMEField = value;
                    this.RaisePropertyChanged("DC_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GUP_CODE {
            get {
                return this.GUP_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.GUP_CODEField, value) != true)) {
                    this.GUP_CODEField = value;
                    this.RaisePropertyChanged("GUP_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GUP_NAME {
            get {
                return this.GUP_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.GUP_NAMEField, value) != true)) {
                    this.GUP_NAMEField = value;
                    this.RaisePropertyChanged("GUP_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO {
            get {
                return this.NOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOField, value) != true)) {
                    this.NOField = value;
                    this.RaisePropertyChanged("NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ROWNUM {
            get {
                return this.ROWNUMField;
            }
            set {
                if ((this.ROWNUMField.Equals(value) != true)) {
                    this.ROWNUMField = value;
                    this.RaisePropertyChanged("ROWNUM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STATUS {
            get {
                return this.STATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.STATUSField, value) != true)) {
                    this.STATUSField = value;
                    this.RaisePropertyChanged("STATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TYPE {
            get {
                return this.TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.TYPEField, value) != true)) {
                    this.TYPEField = value;
                    this.RaisePropertyChanged("TYPE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceedPickFinishTime", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class ExceedPickFinishTime : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CREATE_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUST_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUST_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DC_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DC_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUP_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUP_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PICKFINISHTIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PICK_ORD_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ROWNUMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CREATE_DATE {
            get {
                return this.CREATE_DATEField;
            }
            set {
                if ((this.CREATE_DATEField.Equals(value) != true)) {
                    this.CREATE_DATEField = value;
                    this.RaisePropertyChanged("CREATE_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUST_CODE {
            get {
                return this.CUST_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_CODEField, value) != true)) {
                    this.CUST_CODEField = value;
                    this.RaisePropertyChanged("CUST_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUST_NAME {
            get {
                return this.CUST_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_NAMEField, value) != true)) {
                    this.CUST_NAMEField = value;
                    this.RaisePropertyChanged("CUST_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DC_CODE {
            get {
                return this.DC_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.DC_CODEField, value) != true)) {
                    this.DC_CODEField = value;
                    this.RaisePropertyChanged("DC_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DC_NAME {
            get {
                return this.DC_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.DC_NAMEField, value) != true)) {
                    this.DC_NAMEField = value;
                    this.RaisePropertyChanged("DC_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GUP_CODE {
            get {
                return this.GUP_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.GUP_CODEField, value) != true)) {
                    this.GUP_CODEField = value;
                    this.RaisePropertyChanged("GUP_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GUP_NAME {
            get {
                return this.GUP_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.GUP_NAMEField, value) != true)) {
                    this.GUP_NAMEField = value;
                    this.RaisePropertyChanged("GUP_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PICKFINISHTIME {
            get {
                return this.PICKFINISHTIMEField;
            }
            set {
                if ((object.ReferenceEquals(this.PICKFINISHTIMEField, value) != true)) {
                    this.PICKFINISHTIMEField = value;
                    this.RaisePropertyChanged("PICKFINISHTIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PICK_ORD_NO {
            get {
                return this.PICK_ORD_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PICK_ORD_NOField, value) != true)) {
                    this.PICK_ORD_NOField = value;
                    this.RaisePropertyChanged("PICK_ORD_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ROWNUM {
            get {
                return this.ROWNUMField;
            }
            set {
                if ((this.ROWNUMField.Equals(value) != true)) {
                    this.ROWNUMField = value;
                    this.RaisePropertyChanged("ROWNUM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecuteResult", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class ExecuteResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessed {
            get {
                return this.IsSuccessedField;
            }
            set {
                if ((this.IsSuccessedField.Equals(value) != true)) {
                    this.IsSuccessedField = value;
                    this.RaisePropertyChanged("IsSuccessed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="S03WcfService.S03WcfService")]
    public interface S03WcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/S03WcfService/GetF0020Data", ReplyAction="http://tempuri.org/S03WcfService/GetF0020DataResponse")]
        Wms3pl.WpfClient.ExDataServices.S03WcfService.F0020 GetF0020Data(string msgNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/S03WcfService/GetF0020Data", ReplyAction="http://tempuri.org/S03WcfService/GetF0020DataResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.S03WcfService.F0020> GetF0020DataAsync(string msgNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/S03WcfService/GetOrderIsProblem", ReplyAction="http://tempuri.org/S03WcfService/GetOrderIsProblemResponse")]
        Wms3pl.WpfClient.ExDataServices.S03WcfService.OrderIsProblem[] GetOrderIsProblem(System.DateTime selectDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/S03WcfService/GetOrderIsProblem", ReplyAction="http://tempuri.org/S03WcfService/GetOrderIsProblemResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.S03WcfService.OrderIsProblem[]> GetOrderIsProblemAsync(System.DateTime selectDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/S03WcfService/GetExceedPickFinishTimeDatas", ReplyAction="http://tempuri.org/S03WcfService/GetExceedPickFinishTimeDatasResponse")]
        Wms3pl.WpfClient.ExDataServices.S03WcfService.ExceedPickFinishTime[] GetExceedPickFinishTimeDatas(System.DateTime selectDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/S03WcfService/GetExceedPickFinishTimeDatas", ReplyAction="http://tempuri.org/S03WcfService/GetExceedPickFinishTimeDatasResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.S03WcfService.ExceedPickFinishTime[]> GetExceedPickFinishTimeDatasAsync(System.DateTime selectDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/S03WcfService/InsertSchedule", ReplyAction="http://tempuri.org/S03WcfService/InsertScheduleResponse")]
        Wms3pl.WpfClient.ExDataServices.S03WcfService.ExecuteResult InsertSchedule();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/S03WcfService/InsertSchedule", ReplyAction="http://tempuri.org/S03WcfService/InsertScheduleResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.S03WcfService.ExecuteResult> InsertScheduleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/S03WcfService/InsertSchMessage", ReplyAction="http://tempuri.org/S03WcfService/InsertSchMessageResponse")]
        Wms3pl.WpfClient.ExDataServices.S03WcfService.ExecuteResult InsertSchMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/S03WcfService/InsertSchMessage", ReplyAction="http://tempuri.org/S03WcfService/InsertSchMessageResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.S03WcfService.ExecuteResult> InsertSchMessageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface S03WcfServiceChannel : Wms3pl.WpfClient.ExDataServices.S03WcfService.S03WcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class S03WcfServiceClient : System.ServiceModel.ClientBase<Wms3pl.WpfClient.ExDataServices.S03WcfService.S03WcfService>, Wms3pl.WpfClient.ExDataServices.S03WcfService.S03WcfService {
        
        public S03WcfServiceClient() {
        }
        
        public S03WcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public S03WcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public S03WcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public S03WcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wms3pl.WpfClient.ExDataServices.S03WcfService.F0020 GetF0020Data(string msgNo) {
            return base.Channel.GetF0020Data(msgNo);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.S03WcfService.F0020> GetF0020DataAsync(string msgNo) {
            return base.Channel.GetF0020DataAsync(msgNo);
        }
        
        public Wms3pl.WpfClient.ExDataServices.S03WcfService.OrderIsProblem[] GetOrderIsProblem(System.DateTime selectDate) {
            return base.Channel.GetOrderIsProblem(selectDate);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.S03WcfService.OrderIsProblem[]> GetOrderIsProblemAsync(System.DateTime selectDate) {
            return base.Channel.GetOrderIsProblemAsync(selectDate);
        }
        
        public Wms3pl.WpfClient.ExDataServices.S03WcfService.ExceedPickFinishTime[] GetExceedPickFinishTimeDatas(System.DateTime selectDate) {
            return base.Channel.GetExceedPickFinishTimeDatas(selectDate);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.S03WcfService.ExceedPickFinishTime[]> GetExceedPickFinishTimeDatasAsync(System.DateTime selectDate) {
            return base.Channel.GetExceedPickFinishTimeDatasAsync(selectDate);
        }
        
        public Wms3pl.WpfClient.ExDataServices.S03WcfService.ExecuteResult InsertSchedule() {
            return base.Channel.InsertSchedule();
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.S03WcfService.ExecuteResult> InsertScheduleAsync() {
            return base.Channel.InsertScheduleAsync();
        }
        
        public Wms3pl.WpfClient.ExDataServices.S03WcfService.ExecuteResult InsertSchMessage() {
            return base.Channel.InsertSchMessage();
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.S03WcfService.ExecuteResult> InsertSchMessageAsync() {
            return base.Channel.InsertSchMessageAsync();
        }
    }
}
