//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms3pl.WpfClient.P25.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms3pl.WpfClient.P25.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 序號開通狀態 的當地語系化字串。
        /// </summary>
        public static string ACTIVATED {
            get {
                return ResourceManager.GetString("ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲值卡盒號 的當地語系化字串。
        /// </summary>
        public static string BatchNo {
            get {
                return ResourceManager.GetString("BatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盒號 的當地語系化字串。
        /// </summary>
        public static string BoxSerial {
            get {
                return ResourceManager.GetString("BoxSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號綁儲位 的當地語系化字串。
        /// </summary>
        public static string BUNDLE_SERIALLOC {
            get {
                return ResourceManager.GetString("BUNDLE_SERIALLOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 攝影機編號 的當地語系化字串。
        /// </summary>
        public static string CAMERA_NO {
            get {
                return ResourceManager.GetString("CAMERA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 箱號 的當地語系化字串。
        /// </summary>
        public static string CASE_NO {
            get {
                return ResourceManager.GetString("CASE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 原因 的當地語系化字串。
        /// </summary>
        public static string CAUSE_DESC {
            get {
                return ResourceManager.GetString("CAUSE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 門號 的當地語系化字串。
        /// </summary>
        public static string CELL_NUM {
            get {
                return ResourceManager.GetString("CELL_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 可更換數： 的當地語系化字串。
        /// </summary>
        public static string ChangeCount {
            get {
                return ResourceManager.GetString("ChangeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電腦編號 的當地語系化字串。
        /// </summary>
        public static string CLIENT_IP {
            get {
                return ResourceManager.GetString("CLIENT_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號調入調出設定 的當地語系化字串。
        /// </summary>
        public static string EditableF2501WcfData {
            get {
                return ResourceManager.GetString("EditableF2501WcfData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出查詢結果 的當地語系化字串。
        /// </summary>
        public static string EXPORT_SearchResult {
            get {
                return ResourceManager.GetString("EXPORT_SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認展延 的當地語系化字串。
        /// </summary>
        public static string Extend {
            get {
                return ResourceManager.GetString("Extend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本機預計展延數： 的當地語系化字串。
        /// </summary>
        public static string ExtendCount {
            get {
                return ResourceManager.GetString("ExtendCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 效期展延 的當地語系化字串。
        /// </summary>
        public static string ExtendValidDate {
            get {
                return ResourceManager.GetString("ExtendValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 凍結日期(起) 的當地語系化字串。
        /// </summary>
        public static string FREEZE_BEGIN_DATE {
            get {
                return ResourceManager.GetString("FREEZE_BEGIN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 凍結日期(迄) 的當地語系化字串。
        /// </summary>
        public static string FREEZE_END_DATE {
            get {
                return ResourceManager.GetString("FREEZE_END_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號凍結的日期區間 的當地語系化字串。
        /// </summary>
        public static string FreezeBeginDate {
            get {
                return ResourceManager.GetString("FreezeBeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 凍結序號數量 的當地語系化字串。
        /// </summary>
        public static string FreezeCount {
            get {
                return ResourceManager.GetString("FreezeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 凍結範圍 的當地語系化字串。
        /// </summary>
        public static string FreezeRange {
            get {
                return ResourceManager.GetString("FreezeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入EXCEL 的當地語系化字串。
        /// </summary>
        public static string ImportExcel {
            get {
                return ResourceManager.GetString("ImportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進貨日期 的當地語系化字串。
        /// </summary>
        public static string IN_DATE {
            get {
                return ResourceManager.GetString("IN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 強制更換品號 的當地語系化字串。
        /// </summary>
        public static string IsChangeItemCode {
            get {
                return ResourceManager.GetString("IsChangeItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否通過 的當地語系化字串。
        /// </summary>
        public static string ISPASS_DESC {
            get {
                return ResourceManager.GetString("ISPASS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 全選 的當地語系化字串。
        /// </summary>
        public static string IsSelectedAll {
            get {
                return ResourceManager.GetString("IsSelectedAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品號 的當地語系化字串。
        /// </summary>
        public static string ITEM_CODE {
            get {
                return ResourceManager.GetString("ITEM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品名稱 的當地語系化字串。
        /// </summary>
        public static string ITEM_NAME {
            get {
                return ResourceManager.GetString("ITEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品規格 的當地語系化字串。
        /// </summary>
        public static string ITEM_SPEC {
            get {
                return ResourceManager.GetString("ITEM_SPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品品號 的當地語系化字串。
        /// </summary>
        public static string ItemCode {
            get {
                return ResourceManager.GetString("ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品名 的當地語系化字串。
        /// </summary>
        public static string ITEMNAME {
            get {
                return ResourceManager.GetString("ITEMNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品搜尋 的當地語系化字串。
        /// </summary>
        public static string ItemSearch {
            get {
                return ResourceManager.GetString("ItemSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號類別 的當地語系化字串。
        /// </summary>
        public static string ItemTypeQ {
            get {
                return ResourceManager.GetString("ItemTypeQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲位編號 的當地語系化字串。
        /// </summary>
        public static string LOC_CODE {
            get {
                return ResourceManager.GetString("LOC_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示刷讀通過 的當地語系化字串。
        /// </summary>
        public static string OnlyShowPass {
            get {
                return ResourceManager.GetString("OnlyShowPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 作業類別 的當地語系化字串。
        /// </summary>
        public static string ORD_PROP_NAME {
            get {
                return ResourceManager.GetString("ORD_PROP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盒號 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_BoxSerial {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_BoxSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 門號 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_Cell_Num {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_Cell_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 貨主 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_Cust_Code {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_Cust_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 勾選序號綁儲位必須填寫倉別與儲位 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_EditableF2501WcfData_WarehouseID_LocCode_Required {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_EditableF2501WcfData_WarehouseID_LocCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 業主 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_GUP_Code {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_GUP_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入的貨主編號與目前使用中的貨主編號({0})不同! 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_ImportCUSTCode_Different {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_ImportCUSTCode_Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入的業主編號與目前使用中的業主編號({0})不同! 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_ImportGUPCode_Different {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_ImportGUPCode_Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入要變更的狀態只能為A1(進貨)! 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_ImportSTATUS_Invalid {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_ImportSTATUS_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入表格格式錯誤! 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_ImportTableFormatError {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_ImportTableFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品編號 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_Item_Code {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_Item_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲位編號 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_LocCodeNo {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_LocCodeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 必須選擇物流中心 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_MustSelectDC {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_MustSelectDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無資料! 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_NoData {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 找不到建議儲位! 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_RecommendLocCodeNotFound {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_RecommendLocCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客代 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_RETAIL_CODE {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_RETAIL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存成功! 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_SaveSuccess {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_SerialNo {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入序號! 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_serialNo_Required {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_serialNo_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號格式錯誤! 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_serialNoError {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_serialNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號不存在! 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_serialNoNotExist {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_serialNoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號狀態(輸入A1) 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_SerialStatus {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_SerialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此儲位不存在於選擇的物流中心與倉別 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_StoreNotInWareHouse {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_StoreNotInWareHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 供應商編號 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_Supply {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_Supply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統商 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_SYS_Supply {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_SYS_Supply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單位數量 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_UnitCount {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 效期YYYY/MM/DD(輸入9999/12/31) 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_ValidDate {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_ValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠商編號不存在 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_VNRCodeNotFound {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_VNRCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 倉別編號 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_WarehouseIdNo {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_WarehouseIdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WMS單號 的當地語系化字串。
        /// </summary>
        public static string P2501030000_ViewModel_WMS_NO {
            get {
                return ResourceManager.GetString("P2501030000_ViewModel_WMS_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請檢查檔案是否已開啟 的當地語系化字串。
        /// </summary>
        public static string P2502010000_ViewModel_CheckIsOpenedFile {
            get {
                return ResourceManager.GetString("P2502010000_ViewModel_CheckIsOpenedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前尚無資料匯出! 的當地語系化字串。
        /// </summary>
        public static string P2502010000_ViewModel_NoDataExport {
            get {
                return ResourceManager.GetString("P2502010000_ViewModel_NoDataExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品編號/序號/系統單號/PO單號 至少輸入一項查詢條件 的當地語系化字串。
        /// </summary>
        public static string P2502010000_ViewModel_SearchCondition_Required {
            get {
                return ResourceManager.GetString("P2502010000_ViewModel_SearchCondition_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇儲存路徑 的當地語系化字串。
        /// </summary>
        public static string P2502010000_ViewModel_SelectStoragePath {
            get {
                return ResourceManager.GetString("P2502010000_ViewModel_SelectStoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號主檔查詢- 的當地語系化字串。
        /// </summary>
        public static string P2502010000_ViewModel_SerialFileSearch {
            get {
                return ResourceManager.GetString("P2502010000_ViewModel_SerialFileSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 業主,貨主,商品品號,商品名稱,商品規格 的當地語系化字串。
        /// </summary>
        public static string P2502010000_ViewModel_Title1 {
            get {
                return ResourceManager.GetString("P2502010000_ViewModel_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ,序號狀態,序號 的當地語系化字串。
        /// </summary>
        public static string P2502010000_ViewModel_Title2 {
            get {
                return ResourceManager.GetString("P2502010000_ViewModel_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ,效期 的當地語系化字串。
        /// </summary>
        public static string P2502010000_ViewModel_Title3 {
            get {
                return ResourceManager.GetString("P2502010000_ViewModel_Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ,PO單號,系統單號,進貨日期,作業類別 的當地語系化字串。
        /// </summary>
        public static string P2502010000_ViewModel_Title4 {
            get {
                return ResourceManager.GetString("P2502010000_ViewModel_Title4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ,序號開通狀態,加工單號 的當地語系化字串。
        /// </summary>
        public static string P2502010000_ViewModel_Title5 {
            get {
                return ResourceManager.GetString("P2502010000_ViewModel_Title5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ,供應商,電腦編號,單位 的當地語系化字串。
        /// </summary>
        public static string P2502010000_ViewModel_Title6 {
            get {
                return ResourceManager.GetString("P2502010000_ViewModel_Title6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ,建立日期,建立人員,異動日期,異動人員 的當地語系化字串。
        /// </summary>
        public static string P2502010000_ViewModel_Title7 {
            get {
                return ResourceManager.GetString("P2502010000_ViewModel_Title7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品編號/序號/門號/系統單號/PO單號/儲值卡盒號/盒號 至少輸入一項查詢條件 的當地語系化字串。
        /// </summary>
        public static string P2502020000_ViewModel_SearchCondition_Required {
            get {
                return ResourceManager.GetString("P2502020000_ViewModel_SearchCondition_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號異動查詢- 的當地語系化字串。
        /// </summary>
        public static string P2502020000_ViewModel_SerialModifySearch {
            get {
                return ResourceManager.GetString("P2502020000_ViewModel_SerialModifySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 將清空資料列重新查詢並檢核序號，是否確認？ 的當地語系化字串。
        /// </summary>
        public static string P2503010000_ViewModel_ClearDataAndReCheckSerialNo {
            get {
                return ResourceManager.GetString("P2503010000_ViewModel_ClearDataAndReCheckSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預計展延序號數{0}，是否確認展延？ 的當地語系化字串。
        /// </summary>
        public static string P2503010000_ViewModel_ExtendCount {
            get {
                return ResourceManager.GetString("P2503010000_ViewModel_ExtendCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號已展延 的當地語系化字串。
        /// </summary>
        public static string P2503010000_ViewModel_ExtendSerial {
            get {
                return ResourceManager.GetString("P2503010000_ViewModel_ExtendSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號已更換 的當地語系化字串。
        /// </summary>
        public static string P2503020000_ViewModel_ChangeCount {
            get {
                return ResourceManager.GetString("P2503020000_ViewModel_ChangeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預計更換數{0}，是否確認更換？ 的當地語系化字串。
        /// </summary>
        public static string P2503020000_ViewModel_ExpectChangeCount {
            get {
                return ResourceManager.GetString("P2503020000_ViewModel_ExpectChangeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品號不存在 的當地語系化字串。
        /// </summary>
        public static string P2503020000_ViewModel_ItemCodeNotExist {
            get {
                return ResourceManager.GetString("P2503020000_ViewModel_ItemCodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新序號已存在，不可以更改 的當地語系化字串。
        /// </summary>
        public static string P2503020000_ViewModel_NewSerialNoIsExist {
            get {
                return ResourceManager.GetString("P2503020000_ViewModel_NewSerialNoIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 舊序號檢核失敗 的當地語系化字串。
        /// </summary>
        public static string P2503020000_ViewModel_OldSerialNoCheckError {
            get {
                return ResourceManager.GetString("P2503020000_ViewModel_OldSerialNoCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刷讀資料不可重複（新序號{0}） 的當地語系化字串。
        /// </summary>
        public static string P2503020000_ViewModel_ScanData_Duplicate_New0 {
            get {
                return ResourceManager.GetString("P2503020000_ViewModel_ScanData_Duplicate_New0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刷讀資料不可重複（舊序號{0}） 的當地語系化字串。
        /// </summary>
        public static string P2503020000_ViewModel_ScanData_Duplicate_Old0 {
            get {
                return ResourceManager.GetString("P2503020000_ViewModel_ScanData_Duplicate_Old0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新序號和舊序號相同 的當地語系化字串。
        /// </summary>
        public static string P2503020000_ViewModel_SerialNo_New_Old_TheSame {
            get {
                return ResourceManager.GetString("P2503020000_ViewModel_SerialNo_New_Old_TheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 貼上 的當地語系化字串。
        /// </summary>
        public static string PASTE {
            get {
                return ResourceManager.GetString("PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PO單號 的當地語系化字串。
        /// </summary>
        public static string PO_NO {
            get {
                return ResourceManager.GetString("PO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 加工單號 的當地語系化字串。
        /// </summary>
        public static string PROCESS_NO {
            get {
                return ResourceManager.GetString("PROCESS_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品搜尋 的當地語系化字串。
        /// </summary>
        public static string ProductSearch {
            get {
                return ResourceManager.GetString("ProductSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 管制作業 的當地語系化字串。
        /// </summary>
        public static string RegulatoryWork {
            get {
                return ResourceManager.GetString("RegulatoryWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客戶代號 的當地語系化字串。
        /// </summary>
        public static string RETAIL_CODE {
            get {
                return ResourceManager.GetString("RETAIL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刷讀區域 的當地語系化字串。
        /// </summary>
        public static string ScanArea {
            get {
                return ResourceManager.GetString("ScanArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刷讀結果 的當地語系化字串。
        /// </summary>
        public static string ScanResult {
            get {
                return ResourceManager.GetString("ScanResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號凍結的原因 的當地語系化字串。
        /// </summary>
        public static string SelectedFreezeReason {
            get {
                return ResourceManager.GetString("SelectedFreezeReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號是否已上傳給客戶 的當地語系化字串。
        /// </summary>
        public static string SEND_CUST {
            get {
                return ResourceManager.GetString("SEND_CUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號(起) 的當地語系化字串。
        /// </summary>
        public static string SERIAL_NO_BEGIN {
            get {
                return ResourceManager.GetString("SERIAL_NO_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號範圍 的當地語系化字串。
        /// </summary>
        public static string Serial_No_Range {
            get {
                return ResourceManager.GetString("Serial_No_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號更換檔匯入 的當地語系化字串。
        /// </summary>
        public static string SerialChangeFileImport {
            get {
                return ResourceManager.GetString("SerialChangeFileImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號 的當地語系化字串。
        /// </summary>
        public static string SerialNo {
            get {
                return ResourceManager.GetString("SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號查詢 的當地語系化字串。
        /// </summary>
        public static string SerialNo_Search {
            get {
                return ResourceManager.GetString("SerialNo_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號(迄) 的當地語系化字串。
        /// </summary>
        public static string SerialNoBeginEnd {
            get {
                return ResourceManager.GetString("SerialNoBeginEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新序號 的當地語系化字串。
        /// </summary>
        public static string SerialNoNew {
            get {
                return ResourceManager.GetString("SerialNoNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 舊序號 的當地語系化字串。
        /// </summary>
        public static string SerialNoOld {
            get {
                return ResourceManager.GetString("SerialNoOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號狀態 的當地語系化字串。
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統商 的當地語系化字串。
        /// </summary>
        public static string SYS_NAME {
            get {
                return ResourceManager.GetString("SYS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 3G號碼 的當地語系化字串。
        /// </summary>
        public static string TAG3G {
            get {
                return ResourceManager.GetString("TAG3G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單位 的當地語系化字串。
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 效期 的當地語系化字串。
        /// </summary>
        public static string VALID_DATE {
            get {
                return ResourceManager.GetString("VALID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 驗證通過 的當地語系化字串。
        /// </summary>
        public static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 供應商編號 的當地語系化字串。
        /// </summary>
        public static string VNR_CODE {
            get {
                return ResourceManager.GetString("VNR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 供應商 的當地語系化字串。
        /// </summary>
        public static string VNR_NAME {
            get {
                return ResourceManager.GetString("VNR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 倉別名稱 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_ID {
            get {
                return ResourceManager.GetString("WAREHOUSE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統單號 的當地語系化字串。
        /// </summary>
        public static string WMS_NO {
            get {
                return ResourceManager.GetString("WMS_NO", resourceCulture);
            }
        }
    }
}
