//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms3pl.WpfClient.ExDataServices.P18WcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="F1913", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.F19")]
    [System.SerializableAttribute()]
    public partial class F1913 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BOX_CTRL_NOk__BackingFieldField;
        
        private System.DateTime CRT_DATEk__BackingFieldField;
        
        private string CRT_NAMEk__BackingFieldField;
        
        private string CRT_STAFFk__BackingFieldField;
        
        private string CUST_CODEk__BackingFieldField;
        
        private string DC_CODEk__BackingFieldField;
        
        private System.DateTime ENTER_DATEk__BackingFieldField;
        
        private string GUP_CODEk__BackingFieldField;
        
        private string ITEM_CODEk__BackingFieldField;
        
        private string LOC_CODEk__BackingFieldField;
        
        private string MAKE_NOk__BackingFieldField;
        
        private string PALLET_CTRL_NOk__BackingFieldField;
        
        private long QTYk__BackingFieldField;
        
        private string REMARKk__BackingFieldField;
        
        private string SERIAL_NOk__BackingFieldField;
        
        private System.Nullable<System.DateTime> UPD_DATEk__BackingFieldField;
        
        private string UPD_NAMEk__BackingFieldField;
        
        private string UPD_STAFFk__BackingFieldField;
        
        private System.DateTime VALID_DATEk__BackingFieldField;
        
        private string VNR_CODEk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BOX_CTRL_NO>k__BackingField", IsRequired=true)]
        public string BOX_CTRL_NOk__BackingField {
            get {
                return this.BOX_CTRL_NOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.BOX_CTRL_NOk__BackingFieldField, value) != true)) {
                    this.BOX_CTRL_NOk__BackingFieldField = value;
                    this.RaisePropertyChanged("BOX_CTRL_NOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CRT_DATE>k__BackingField", IsRequired=true)]
        public System.DateTime CRT_DATEk__BackingField {
            get {
                return this.CRT_DATEk__BackingFieldField;
            }
            set {
                if ((this.CRT_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.CRT_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("CRT_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CRT_NAME>k__BackingField", IsRequired=true)]
        public string CRT_NAMEk__BackingField {
            get {
                return this.CRT_NAMEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CRT_NAMEk__BackingFieldField, value) != true)) {
                    this.CRT_NAMEk__BackingFieldField = value;
                    this.RaisePropertyChanged("CRT_NAMEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CRT_STAFF>k__BackingField", IsRequired=true)]
        public string CRT_STAFFk__BackingField {
            get {
                return this.CRT_STAFFk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CRT_STAFFk__BackingFieldField, value) != true)) {
                    this.CRT_STAFFk__BackingFieldField = value;
                    this.RaisePropertyChanged("CRT_STAFFk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CUST_CODE>k__BackingField", IsRequired=true)]
        public string CUST_CODEk__BackingField {
            get {
                return this.CUST_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_CODEk__BackingFieldField, value) != true)) {
                    this.CUST_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("CUST_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DC_CODE>k__BackingField", IsRequired=true)]
        public string DC_CODEk__BackingField {
            get {
                return this.DC_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DC_CODEk__BackingFieldField, value) != true)) {
                    this.DC_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("DC_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ENTER_DATE>k__BackingField", IsRequired=true)]
        public System.DateTime ENTER_DATEk__BackingField {
            get {
                return this.ENTER_DATEk__BackingFieldField;
            }
            set {
                if ((this.ENTER_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.ENTER_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("ENTER_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<GUP_CODE>k__BackingField", IsRequired=true)]
        public string GUP_CODEk__BackingField {
            get {
                return this.GUP_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.GUP_CODEk__BackingFieldField, value) != true)) {
                    this.GUP_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("GUP_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ITEM_CODE>k__BackingField", IsRequired=true)]
        public string ITEM_CODEk__BackingField {
            get {
                return this.ITEM_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_CODEk__BackingFieldField, value) != true)) {
                    this.ITEM_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("ITEM_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LOC_CODE>k__BackingField", IsRequired=true)]
        public string LOC_CODEk__BackingField {
            get {
                return this.LOC_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LOC_CODEk__BackingFieldField, value) != true)) {
                    this.LOC_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("LOC_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MAKE_NO>k__BackingField", IsRequired=true)]
        public string MAKE_NOk__BackingField {
            get {
                return this.MAKE_NOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.MAKE_NOk__BackingFieldField, value) != true)) {
                    this.MAKE_NOk__BackingFieldField = value;
                    this.RaisePropertyChanged("MAKE_NOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PALLET_CTRL_NO>k__BackingField", IsRequired=true)]
        public string PALLET_CTRL_NOk__BackingField {
            get {
                return this.PALLET_CTRL_NOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PALLET_CTRL_NOk__BackingFieldField, value) != true)) {
                    this.PALLET_CTRL_NOk__BackingFieldField = value;
                    this.RaisePropertyChanged("PALLET_CTRL_NOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<QTY>k__BackingField", IsRequired=true)]
        public long QTYk__BackingField {
            get {
                return this.QTYk__BackingFieldField;
            }
            set {
                if ((this.QTYk__BackingFieldField.Equals(value) != true)) {
                    this.QTYk__BackingFieldField = value;
                    this.RaisePropertyChanged("QTYk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<REMARK>k__BackingField", IsRequired=true)]
        public string REMARKk__BackingField {
            get {
                return this.REMARKk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.REMARKk__BackingFieldField, value) != true)) {
                    this.REMARKk__BackingFieldField = value;
                    this.RaisePropertyChanged("REMARKk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SERIAL_NO>k__BackingField", IsRequired=true)]
        public string SERIAL_NOk__BackingField {
            get {
                return this.SERIAL_NOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SERIAL_NOk__BackingFieldField, value) != true)) {
                    this.SERIAL_NOk__BackingFieldField = value;
                    this.RaisePropertyChanged("SERIAL_NOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UPD_DATE>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> UPD_DATEk__BackingField {
            get {
                return this.UPD_DATEk__BackingFieldField;
            }
            set {
                if ((this.UPD_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.UPD_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("UPD_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UPD_NAME>k__BackingField", IsRequired=true)]
        public string UPD_NAMEk__BackingField {
            get {
                return this.UPD_NAMEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UPD_NAMEk__BackingFieldField, value) != true)) {
                    this.UPD_NAMEk__BackingFieldField = value;
                    this.RaisePropertyChanged("UPD_NAMEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UPD_STAFF>k__BackingField", IsRequired=true)]
        public string UPD_STAFFk__BackingField {
            get {
                return this.UPD_STAFFk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UPD_STAFFk__BackingFieldField, value) != true)) {
                    this.UPD_STAFFk__BackingFieldField = value;
                    this.RaisePropertyChanged("UPD_STAFFk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<VALID_DATE>k__BackingField", IsRequired=true)]
        public System.DateTime VALID_DATEk__BackingField {
            get {
                return this.VALID_DATEk__BackingFieldField;
            }
            set {
                if ((this.VALID_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.VALID_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("VALID_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<VNR_CODE>k__BackingField", IsRequired=true)]
        public string VNR_CODEk__BackingField {
            get {
                return this.VNR_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.VNR_CODEk__BackingFieldField, value) != true)) {
                    this.VNR_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("VNR_CODEk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecuteResult", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class ExecuteResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessed {
            get {
                return this.IsSuccessedField;
            }
            set {
                if ((this.IsSuccessedField.Equals(value) != true)) {
                    this.IsSuccessedField = value;
                    this.RaisePropertyChanged("IsSuccessed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="P180301ImportData", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class P180301ImportData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EnterDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemVerificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocMixItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocVerificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MixBatchnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ROWNUMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ValidDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarehouseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarehouseNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EnterDate {
            get {
                return this.EnterDateField;
            }
            set {
                if ((this.EnterDateField.Equals(value) != true)) {
                    this.EnterDateField = value;
                    this.RaisePropertyChanged("EnterDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemVerification {
            get {
                return this.ItemVerificationField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemVerificationField, value) != true)) {
                    this.ItemVerificationField = value;
                    this.RaisePropertyChanged("ItemVerification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocCode {
            get {
                return this.LocCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocCodeField, value) != true)) {
                    this.LocCodeField = value;
                    this.RaisePropertyChanged("LocCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocMixItem {
            get {
                return this.LocMixItemField;
            }
            set {
                if ((object.ReferenceEquals(this.LocMixItemField, value) != true)) {
                    this.LocMixItemField = value;
                    this.RaisePropertyChanged("LocMixItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocVerification {
            get {
                return this.LocVerificationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocVerificationField, value) != true)) {
                    this.LocVerificationField = value;
                    this.RaisePropertyChanged("LocVerification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeNo {
            get {
                return this.MakeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeNoField, value) != true)) {
                    this.MakeNoField = value;
                    this.RaisePropertyChanged("MakeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MixBatchno {
            get {
                return this.MixBatchnoField;
            }
            set {
                if ((object.ReferenceEquals(this.MixBatchnoField, value) != true)) {
                    this.MixBatchnoField = value;
                    this.RaisePropertyChanged("MixBatchno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((object.ReferenceEquals(this.QtyField, value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ROWNUM {
            get {
                return this.ROWNUMField;
            }
            set {
                if ((this.ROWNUMField.Equals(value) != true)) {
                    this.ROWNUMField = value;
                    this.RaisePropertyChanged("ROWNUM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ValidDate {
            get {
                return this.ValidDateField;
            }
            set {
                if ((this.ValidDateField.Equals(value) != true)) {
                    this.ValidDateField = value;
                    this.RaisePropertyChanged("ValidDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarehouseId {
            get {
                return this.WarehouseIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseIdField, value) != true)) {
                    this.WarehouseIdField = value;
                    this.RaisePropertyChanged("WarehouseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarehouseName {
            get {
                return this.WarehouseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseNameField, value) != true)) {
                    this.WarehouseNameField = value;
                    this.RaisePropertyChanged("WarehouseName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockAbnormalData", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class StockAbnormalData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALLOCATION_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ALLOCATION_SEQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CRT_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CRT_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUST_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DC_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUP_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITEM_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITEM_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MAKE_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MEMOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROC_FLAGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROC_FLAG_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROC_WMS_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ROWNUMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SERIAL_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SRC_LOC_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SRC_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SRC_TYPE_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SRC_WAREHOUSE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SRC_WAREHOUSE_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SRC_WMS_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UPD_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPD_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VALID_DATEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALLOCATION_NO {
            get {
                return this.ALLOCATION_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.ALLOCATION_NOField, value) != true)) {
                    this.ALLOCATION_NOField = value;
                    this.RaisePropertyChanged("ALLOCATION_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ALLOCATION_SEQ {
            get {
                return this.ALLOCATION_SEQField;
            }
            set {
                if ((this.ALLOCATION_SEQField.Equals(value) != true)) {
                    this.ALLOCATION_SEQField = value;
                    this.RaisePropertyChanged("ALLOCATION_SEQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CRT_DATE {
            get {
                return this.CRT_DATEField;
            }
            set {
                if ((this.CRT_DATEField.Equals(value) != true)) {
                    this.CRT_DATEField = value;
                    this.RaisePropertyChanged("CRT_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRT_NAME {
            get {
                return this.CRT_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.CRT_NAMEField, value) != true)) {
                    this.CRT_NAMEField = value;
                    this.RaisePropertyChanged("CRT_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUST_CODE {
            get {
                return this.CUST_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_CODEField, value) != true)) {
                    this.CUST_CODEField = value;
                    this.RaisePropertyChanged("CUST_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DC_CODE {
            get {
                return this.DC_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.DC_CODEField, value) != true)) {
                    this.DC_CODEField = value;
                    this.RaisePropertyChanged("DC_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GUP_CODE {
            get {
                return this.GUP_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.GUP_CODEField, value) != true)) {
                    this.GUP_CODEField = value;
                    this.RaisePropertyChanged("GUP_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITEM_CODE {
            get {
                return this.ITEM_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_CODEField, value) != true)) {
                    this.ITEM_CODEField = value;
                    this.RaisePropertyChanged("ITEM_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITEM_NAME {
            get {
                return this.ITEM_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_NAMEField, value) != true)) {
                    this.ITEM_NAMEField = value;
                    this.RaisePropertyChanged("ITEM_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MAKE_NO {
            get {
                return this.MAKE_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.MAKE_NOField, value) != true)) {
                    this.MAKE_NOField = value;
                    this.RaisePropertyChanged("MAKE_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MEMO {
            get {
                return this.MEMOField;
            }
            set {
                if ((object.ReferenceEquals(this.MEMOField, value) != true)) {
                    this.MEMOField = value;
                    this.RaisePropertyChanged("MEMO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROC_FLAG {
            get {
                return this.PROC_FLAGField;
            }
            set {
                if ((object.ReferenceEquals(this.PROC_FLAGField, value) != true)) {
                    this.PROC_FLAGField = value;
                    this.RaisePropertyChanged("PROC_FLAG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROC_FLAG_NAME {
            get {
                return this.PROC_FLAG_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.PROC_FLAG_NAMEField, value) != true)) {
                    this.PROC_FLAG_NAMEField = value;
                    this.RaisePropertyChanged("PROC_FLAG_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROC_WMS_NO {
            get {
                return this.PROC_WMS_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PROC_WMS_NOField, value) != true)) {
                    this.PROC_WMS_NOField = value;
                    this.RaisePropertyChanged("PROC_WMS_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QTY {
            get {
                return this.QTYField;
            }
            set {
                if ((this.QTYField.Equals(value) != true)) {
                    this.QTYField = value;
                    this.RaisePropertyChanged("QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ROWNUM {
            get {
                return this.ROWNUMField;
            }
            set {
                if ((this.ROWNUMField.Equals(value) != true)) {
                    this.ROWNUMField = value;
                    this.RaisePropertyChanged("ROWNUM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SERIAL_NO {
            get {
                return this.SERIAL_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.SERIAL_NOField, value) != true)) {
                    this.SERIAL_NOField = value;
                    this.RaisePropertyChanged("SERIAL_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SRC_LOC_CODE {
            get {
                return this.SRC_LOC_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.SRC_LOC_CODEField, value) != true)) {
                    this.SRC_LOC_CODEField = value;
                    this.RaisePropertyChanged("SRC_LOC_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SRC_TYPE {
            get {
                return this.SRC_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.SRC_TYPEField, value) != true)) {
                    this.SRC_TYPEField = value;
                    this.RaisePropertyChanged("SRC_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SRC_TYPE_NAME {
            get {
                return this.SRC_TYPE_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.SRC_TYPE_NAMEField, value) != true)) {
                    this.SRC_TYPE_NAMEField = value;
                    this.RaisePropertyChanged("SRC_TYPE_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SRC_WAREHOUSE_ID {
            get {
                return this.SRC_WAREHOUSE_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.SRC_WAREHOUSE_IDField, value) != true)) {
                    this.SRC_WAREHOUSE_IDField = value;
                    this.RaisePropertyChanged("SRC_WAREHOUSE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SRC_WAREHOUSE_NAME {
            get {
                return this.SRC_WAREHOUSE_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.SRC_WAREHOUSE_NAMEField, value) != true)) {
                    this.SRC_WAREHOUSE_NAMEField = value;
                    this.RaisePropertyChanged("SRC_WAREHOUSE_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SRC_WMS_NO {
            get {
                return this.SRC_WMS_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.SRC_WMS_NOField, value) != true)) {
                    this.SRC_WMS_NOField = value;
                    this.RaisePropertyChanged("SRC_WMS_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UPD_DATE {
            get {
                return this.UPD_DATEField;
            }
            set {
                if ((this.UPD_DATEField.Equals(value) != true)) {
                    this.UPD_DATEField = value;
                    this.RaisePropertyChanged("UPD_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPD_NAME {
            get {
                return this.UPD_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.UPD_NAMEField, value) != true)) {
                    this.UPD_NAMEField = value;
                    this.RaisePropertyChanged("UPD_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VALID_DATE {
            get {
                return this.VALID_DATEField;
            }
            set {
                if ((this.VALID_DATEField.Equals(value) != true)) {
                    this.VALID_DATEField = value;
                    this.RaisePropertyChanged("VALID_DATE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="P18WcfService.P18WcfService")]
    public interface P18WcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P18WcfService/GetF1913Data", ReplyAction="http://tempuri.org/P18WcfService/GetF1913DataResponse")]
        Wms3pl.WpfClient.ExDataServices.P18WcfService.F1913[] GetF1913Data(Wms3pl.WpfClient.ExDataServices.P18WcfService.F1913 f1913s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P18WcfService/GetF1913Data", ReplyAction="http://tempuri.org/P18WcfService/GetF1913DataResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P18WcfService.F1913[]> GetF1913DataAsync(Wms3pl.WpfClient.ExDataServices.P18WcfService.F1913 f1913s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P18WcfService/UpdateValidDateAndBatchNo", ReplyAction="http://tempuri.org/P18WcfService/UpdateValidDateAndBatchNoResponse")]
        Wms3pl.WpfClient.ExDataServices.P18WcfService.ExecuteResult UpdateValidDateAndBatchNo(Wms3pl.WpfClient.ExDataServices.P18WcfService.F1913 f1913s, System.DateTime newValidDate, string newMakeNo, long NewQTY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P18WcfService/UpdateValidDateAndBatchNo", ReplyAction="http://tempuri.org/P18WcfService/UpdateValidDateAndBatchNoResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P18WcfService.ExecuteResult> UpdateValidDateAndBatchNoAsync(Wms3pl.WpfClient.ExDataServices.P18WcfService.F1913 f1913s, System.DateTime newValidDate, string newMakeNo, long NewQTY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P18WcfService/InsertF200101Data", ReplyAction="http://tempuri.org/P18WcfService/InsertF200101DataResponse")]
        Wms3pl.WpfClient.ExDataServices.P18WcfService.ExecuteResult InsertF200101Data(string dcCode, string gupCode, string custCode, Wms3pl.WpfClient.ExDataServices.P18WcfService.P180301ImportData[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P18WcfService/InsertF200101Data", ReplyAction="http://tempuri.org/P18WcfService/InsertF200101DataResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P18WcfService.ExecuteResult> InsertF200101DataAsync(string dcCode, string gupCode, string custCode, Wms3pl.WpfClient.ExDataServices.P18WcfService.P180301ImportData[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P18WcfService/UpdateF191302", ReplyAction="http://tempuri.org/P18WcfService/UpdateF191302Response")]
        Wms3pl.WpfClient.ExDataServices.P18WcfService.ExecuteResult UpdateF191302(Wms3pl.WpfClient.ExDataServices.P18WcfService.StockAbnormalData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P18WcfService/UpdateF191302", ReplyAction="http://tempuri.org/P18WcfService/UpdateF191302Response")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P18WcfService.ExecuteResult> UpdateF191302Async(Wms3pl.WpfClient.ExDataServices.P18WcfService.StockAbnormalData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P18WcfService/CreateInventory", ReplyAction="http://tempuri.org/P18WcfService/CreateInventoryResponse")]
        Wms3pl.WpfClient.ExDataServices.P18WcfService.ExecuteResult CreateInventory(string dcCode, Wms3pl.WpfClient.ExDataServices.P18WcfService.StockAbnormalData[] datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P18WcfService/CreateInventory", ReplyAction="http://tempuri.org/P18WcfService/CreateInventoryResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P18WcfService.ExecuteResult> CreateInventoryAsync(string dcCode, Wms3pl.WpfClient.ExDataServices.P18WcfService.StockAbnormalData[] datas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface P18WcfServiceChannel : Wms3pl.WpfClient.ExDataServices.P18WcfService.P18WcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class P18WcfServiceClient : System.ServiceModel.ClientBase<Wms3pl.WpfClient.ExDataServices.P18WcfService.P18WcfService>, Wms3pl.WpfClient.ExDataServices.P18WcfService.P18WcfService {
        
        public P18WcfServiceClient() {
        }
        
        public P18WcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public P18WcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public P18WcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public P18WcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wms3pl.WpfClient.ExDataServices.P18WcfService.F1913[] GetF1913Data(Wms3pl.WpfClient.ExDataServices.P18WcfService.F1913 f1913s) {
            return base.Channel.GetF1913Data(f1913s);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P18WcfService.F1913[]> GetF1913DataAsync(Wms3pl.WpfClient.ExDataServices.P18WcfService.F1913 f1913s) {
            return base.Channel.GetF1913DataAsync(f1913s);
        }
        
        public Wms3pl.WpfClient.ExDataServices.P18WcfService.ExecuteResult UpdateValidDateAndBatchNo(Wms3pl.WpfClient.ExDataServices.P18WcfService.F1913 f1913s, System.DateTime newValidDate, string newMakeNo, long NewQTY) {
            return base.Channel.UpdateValidDateAndBatchNo(f1913s, newValidDate, newMakeNo, NewQTY);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P18WcfService.ExecuteResult> UpdateValidDateAndBatchNoAsync(Wms3pl.WpfClient.ExDataServices.P18WcfService.F1913 f1913s, System.DateTime newValidDate, string newMakeNo, long NewQTY) {
            return base.Channel.UpdateValidDateAndBatchNoAsync(f1913s, newValidDate, newMakeNo, NewQTY);
        }
        
        public Wms3pl.WpfClient.ExDataServices.P18WcfService.ExecuteResult InsertF200101Data(string dcCode, string gupCode, string custCode, Wms3pl.WpfClient.ExDataServices.P18WcfService.P180301ImportData[] data) {
            return base.Channel.InsertF200101Data(dcCode, gupCode, custCode, data);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P18WcfService.ExecuteResult> InsertF200101DataAsync(string dcCode, string gupCode, string custCode, Wms3pl.WpfClient.ExDataServices.P18WcfService.P180301ImportData[] data) {
            return base.Channel.InsertF200101DataAsync(dcCode, gupCode, custCode, data);
        }
        
        public Wms3pl.WpfClient.ExDataServices.P18WcfService.ExecuteResult UpdateF191302(Wms3pl.WpfClient.ExDataServices.P18WcfService.StockAbnormalData data) {
            return base.Channel.UpdateF191302(data);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P18WcfService.ExecuteResult> UpdateF191302Async(Wms3pl.WpfClient.ExDataServices.P18WcfService.StockAbnormalData data) {
            return base.Channel.UpdateF191302Async(data);
        }
        
        public Wms3pl.WpfClient.ExDataServices.P18WcfService.ExecuteResult CreateInventory(string dcCode, Wms3pl.WpfClient.ExDataServices.P18WcfService.StockAbnormalData[] datas) {
            return base.Channel.CreateInventory(dcCode, datas);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P18WcfService.ExecuteResult> CreateInventoryAsync(string dcCode, Wms3pl.WpfClient.ExDataServices.P18WcfService.StockAbnormalData[] datas) {
            return base.Channel.CreateInventoryAsync(dcCode, datas);
        }
    }
}
