//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms3pl.WpfClient.ExDataServices.P01WcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="F010101Data", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class F010101Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ADDRESSk__BackingFieldField;
        
        private string BUSPERk__BackingFieldField;
        
        private string CONTACT_TELk__BackingFieldField;
        
        private System.DateTime CRT_DATEk__BackingFieldField;
        
        private string CRT_NAMEk__BackingFieldField;
        
        private string CRT_STAFFk__BackingFieldField;
        
        private string CUST_CODEk__BackingFieldField;
        
        private string CUST_ORD_NOk__BackingFieldField;
        
        private string DC_CODEk__BackingFieldField;
        
        private System.DateTime DELIVER_DATEk__BackingFieldField;
        
        private string GUP_CODEk__BackingFieldField;
        
        private System.DateTime INVOICE_DATEk__BackingFieldField;
        
        private string INVO_TYPEk__BackingFieldField;
        
        private string INV_ADDRESSk__BackingFieldField;
        
        private string MEMOk__BackingFieldField;
        
        private string ORD_PROPk__BackingFieldField;
        
        private string PAY_TYPEk__BackingFieldField;
        
        private string SHOP_CAUSEk__BackingFieldField;
        
        private System.DateTime SHOP_DATEk__BackingFieldField;
        
        private string SHOP_NOk__BackingFieldField;
        
        private string STATUSk__BackingFieldField;
        
        private string TAX_TYPEk__BackingFieldField;
        
        private string TELk__BackingFieldField;
        
        private System.Nullable<System.DateTime> UPD_DATEk__BackingFieldField;
        
        private string UPD_NAMEk__BackingFieldField;
        
        private string UPD_STAFFk__BackingFieldField;
        
        private string VNR_CODEk__BackingFieldField;
        
        private string VNR_NAMEk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ADDRESS>k__BackingField", IsRequired=true)]
        public string ADDRESSk__BackingField {
            get {
                return this.ADDRESSk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ADDRESSk__BackingFieldField, value) != true)) {
                    this.ADDRESSk__BackingFieldField = value;
                    this.RaisePropertyChanged("ADDRESSk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BUSPER>k__BackingField", IsRequired=true)]
        public string BUSPERk__BackingField {
            get {
                return this.BUSPERk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.BUSPERk__BackingFieldField, value) != true)) {
                    this.BUSPERk__BackingFieldField = value;
                    this.RaisePropertyChanged("BUSPERk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CONTACT_TEL>k__BackingField", IsRequired=true)]
        public string CONTACT_TELk__BackingField {
            get {
                return this.CONTACT_TELk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CONTACT_TELk__BackingFieldField, value) != true)) {
                    this.CONTACT_TELk__BackingFieldField = value;
                    this.RaisePropertyChanged("CONTACT_TELk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CRT_DATE>k__BackingField", IsRequired=true)]
        public System.DateTime CRT_DATEk__BackingField {
            get {
                return this.CRT_DATEk__BackingFieldField;
            }
            set {
                if ((this.CRT_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.CRT_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("CRT_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CRT_NAME>k__BackingField", IsRequired=true)]
        public string CRT_NAMEk__BackingField {
            get {
                return this.CRT_NAMEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CRT_NAMEk__BackingFieldField, value) != true)) {
                    this.CRT_NAMEk__BackingFieldField = value;
                    this.RaisePropertyChanged("CRT_NAMEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CRT_STAFF>k__BackingField", IsRequired=true)]
        public string CRT_STAFFk__BackingField {
            get {
                return this.CRT_STAFFk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CRT_STAFFk__BackingFieldField, value) != true)) {
                    this.CRT_STAFFk__BackingFieldField = value;
                    this.RaisePropertyChanged("CRT_STAFFk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CUST_CODE>k__BackingField", IsRequired=true)]
        public string CUST_CODEk__BackingField {
            get {
                return this.CUST_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_CODEk__BackingFieldField, value) != true)) {
                    this.CUST_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("CUST_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CUST_ORD_NO>k__BackingField", IsRequired=true)]
        public string CUST_ORD_NOk__BackingField {
            get {
                return this.CUST_ORD_NOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_ORD_NOk__BackingFieldField, value) != true)) {
                    this.CUST_ORD_NOk__BackingFieldField = value;
                    this.RaisePropertyChanged("CUST_ORD_NOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DC_CODE>k__BackingField", IsRequired=true)]
        public string DC_CODEk__BackingField {
            get {
                return this.DC_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DC_CODEk__BackingFieldField, value) != true)) {
                    this.DC_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("DC_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DELIVER_DATE>k__BackingField", IsRequired=true)]
        public System.DateTime DELIVER_DATEk__BackingField {
            get {
                return this.DELIVER_DATEk__BackingFieldField;
            }
            set {
                if ((this.DELIVER_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.DELIVER_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("DELIVER_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<GUP_CODE>k__BackingField", IsRequired=true)]
        public string GUP_CODEk__BackingField {
            get {
                return this.GUP_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.GUP_CODEk__BackingFieldField, value) != true)) {
                    this.GUP_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("GUP_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<INVOICE_DATE>k__BackingField", IsRequired=true)]
        public System.DateTime INVOICE_DATEk__BackingField {
            get {
                return this.INVOICE_DATEk__BackingFieldField;
            }
            set {
                if ((this.INVOICE_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.INVOICE_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("INVOICE_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<INVO_TYPE>k__BackingField", IsRequired=true)]
        public string INVO_TYPEk__BackingField {
            get {
                return this.INVO_TYPEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.INVO_TYPEk__BackingFieldField, value) != true)) {
                    this.INVO_TYPEk__BackingFieldField = value;
                    this.RaisePropertyChanged("INVO_TYPEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<INV_ADDRESS>k__BackingField", IsRequired=true)]
        public string INV_ADDRESSk__BackingField {
            get {
                return this.INV_ADDRESSk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.INV_ADDRESSk__BackingFieldField, value) != true)) {
                    this.INV_ADDRESSk__BackingFieldField = value;
                    this.RaisePropertyChanged("INV_ADDRESSk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MEMO>k__BackingField", IsRequired=true)]
        public string MEMOk__BackingField {
            get {
                return this.MEMOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.MEMOk__BackingFieldField, value) != true)) {
                    this.MEMOk__BackingFieldField = value;
                    this.RaisePropertyChanged("MEMOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ORD_PROP>k__BackingField", IsRequired=true)]
        public string ORD_PROPk__BackingField {
            get {
                return this.ORD_PROPk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ORD_PROPk__BackingFieldField, value) != true)) {
                    this.ORD_PROPk__BackingFieldField = value;
                    this.RaisePropertyChanged("ORD_PROPk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PAY_TYPE>k__BackingField", IsRequired=true)]
        public string PAY_TYPEk__BackingField {
            get {
                return this.PAY_TYPEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PAY_TYPEk__BackingFieldField, value) != true)) {
                    this.PAY_TYPEk__BackingFieldField = value;
                    this.RaisePropertyChanged("PAY_TYPEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SHOP_CAUSE>k__BackingField", IsRequired=true)]
        public string SHOP_CAUSEk__BackingField {
            get {
                return this.SHOP_CAUSEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SHOP_CAUSEk__BackingFieldField, value) != true)) {
                    this.SHOP_CAUSEk__BackingFieldField = value;
                    this.RaisePropertyChanged("SHOP_CAUSEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SHOP_DATE>k__BackingField", IsRequired=true)]
        public System.DateTime SHOP_DATEk__BackingField {
            get {
                return this.SHOP_DATEk__BackingFieldField;
            }
            set {
                if ((this.SHOP_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.SHOP_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("SHOP_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SHOP_NO>k__BackingField", IsRequired=true)]
        public string SHOP_NOk__BackingField {
            get {
                return this.SHOP_NOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SHOP_NOk__BackingFieldField, value) != true)) {
                    this.SHOP_NOk__BackingFieldField = value;
                    this.RaisePropertyChanged("SHOP_NOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<STATUS>k__BackingField", IsRequired=true)]
        public string STATUSk__BackingField {
            get {
                return this.STATUSk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.STATUSk__BackingFieldField, value) != true)) {
                    this.STATUSk__BackingFieldField = value;
                    this.RaisePropertyChanged("STATUSk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TAX_TYPE>k__BackingField", IsRequired=true)]
        public string TAX_TYPEk__BackingField {
            get {
                return this.TAX_TYPEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.TAX_TYPEk__BackingFieldField, value) != true)) {
                    this.TAX_TYPEk__BackingFieldField = value;
                    this.RaisePropertyChanged("TAX_TYPEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TEL>k__BackingField", IsRequired=true)]
        public string TELk__BackingField {
            get {
                return this.TELk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.TELk__BackingFieldField, value) != true)) {
                    this.TELk__BackingFieldField = value;
                    this.RaisePropertyChanged("TELk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UPD_DATE>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> UPD_DATEk__BackingField {
            get {
                return this.UPD_DATEk__BackingFieldField;
            }
            set {
                if ((this.UPD_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.UPD_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("UPD_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UPD_NAME>k__BackingField", IsRequired=true)]
        public string UPD_NAMEk__BackingField {
            get {
                return this.UPD_NAMEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UPD_NAMEk__BackingFieldField, value) != true)) {
                    this.UPD_NAMEk__BackingFieldField = value;
                    this.RaisePropertyChanged("UPD_NAMEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UPD_STAFF>k__BackingField", IsRequired=true)]
        public string UPD_STAFFk__BackingField {
            get {
                return this.UPD_STAFFk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UPD_STAFFk__BackingFieldField, value) != true)) {
                    this.UPD_STAFFk__BackingFieldField = value;
                    this.RaisePropertyChanged("UPD_STAFFk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<VNR_CODE>k__BackingField", IsRequired=true)]
        public string VNR_CODEk__BackingField {
            get {
                return this.VNR_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.VNR_CODEk__BackingFieldField, value) != true)) {
                    this.VNR_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("VNR_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<VNR_NAME>k__BackingField", IsRequired=true)]
        public string VNR_NAMEk__BackingField {
            get {
                return this.VNR_NAMEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.VNR_NAMEk__BackingFieldField, value) != true)) {
                    this.VNR_NAMEk__BackingFieldField = value;
                    this.RaisePropertyChanged("VNR_NAMEk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="F010102Data", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class F010102Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ITEM_CODEk__BackingFieldField;
        
        private string ITEM_COLORk__BackingFieldField;
        
        private string ITEM_NAMEk__BackingFieldField;
        
        private string ITEM_SIZEk__BackingFieldField;
        
        private string ITEM_SPECk__BackingFieldField;
        
        private string SHOP_NOk__BackingFieldField;
        
        private int SHOP_QTYk__BackingFieldField;
        
        private string SHOP_SEQk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ITEM_CODE>k__BackingField", IsRequired=true)]
        public string ITEM_CODEk__BackingField {
            get {
                return this.ITEM_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_CODEk__BackingFieldField, value) != true)) {
                    this.ITEM_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("ITEM_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ITEM_COLOR>k__BackingField", IsRequired=true)]
        public string ITEM_COLORk__BackingField {
            get {
                return this.ITEM_COLORk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_COLORk__BackingFieldField, value) != true)) {
                    this.ITEM_COLORk__BackingFieldField = value;
                    this.RaisePropertyChanged("ITEM_COLORk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ITEM_NAME>k__BackingField", IsRequired=true)]
        public string ITEM_NAMEk__BackingField {
            get {
                return this.ITEM_NAMEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_NAMEk__BackingFieldField, value) != true)) {
                    this.ITEM_NAMEk__BackingFieldField = value;
                    this.RaisePropertyChanged("ITEM_NAMEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ITEM_SIZE>k__BackingField", IsRequired=true)]
        public string ITEM_SIZEk__BackingField {
            get {
                return this.ITEM_SIZEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_SIZEk__BackingFieldField, value) != true)) {
                    this.ITEM_SIZEk__BackingFieldField = value;
                    this.RaisePropertyChanged("ITEM_SIZEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ITEM_SPEC>k__BackingField", IsRequired=true)]
        public string ITEM_SPECk__BackingField {
            get {
                return this.ITEM_SPECk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_SPECk__BackingFieldField, value) != true)) {
                    this.ITEM_SPECk__BackingFieldField = value;
                    this.RaisePropertyChanged("ITEM_SPECk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SHOP_NO>k__BackingField", IsRequired=true)]
        public string SHOP_NOk__BackingField {
            get {
                return this.SHOP_NOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SHOP_NOk__BackingFieldField, value) != true)) {
                    this.SHOP_NOk__BackingFieldField = value;
                    this.RaisePropertyChanged("SHOP_NOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SHOP_QTY>k__BackingField", IsRequired=true)]
        public int SHOP_QTYk__BackingField {
            get {
                return this.SHOP_QTYk__BackingFieldField;
            }
            set {
                if ((this.SHOP_QTYk__BackingFieldField.Equals(value) != true)) {
                    this.SHOP_QTYk__BackingFieldField = value;
                    this.RaisePropertyChanged("SHOP_QTYk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SHOP_SEQ>k__BackingField", IsRequired=true)]
        public string SHOP_SEQk__BackingField {
            get {
                return this.SHOP_SEQk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SHOP_SEQk__BackingFieldField, value) != true)) {
                    this.SHOP_SEQk__BackingFieldField = value;
                    this.RaisePropertyChanged("SHOP_SEQk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecuteResult", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class ExecuteResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessed {
            get {
                return this.IsSuccessedField;
            }
            set {
                if ((this.IsSuccessedField.Equals(value) != true)) {
                    this.IsSuccessedField = value;
                    this.RaisePropertyChanged("IsSuccessed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="F010201Data", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class F010201Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BOOKING_IN_PERIODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CRT_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CRT_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CRT_STAFFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUST_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUST_COSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUST_ORD_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DC_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DC_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DELIVER_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EDI_FLAGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FAST_PASS_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUP_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MEMOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ORD_PROPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SHOP_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SHOP_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SOURCE_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SOURCE_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SOURCE_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STATUSNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime STOCK_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STOCK_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UPD_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPD_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPD_STAFFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VNR_ADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VNR_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VNR_NAMEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BOOKING_IN_PERIOD {
            get {
                return this.BOOKING_IN_PERIODField;
            }
            set {
                if ((object.ReferenceEquals(this.BOOKING_IN_PERIODField, value) != true)) {
                    this.BOOKING_IN_PERIODField = value;
                    this.RaisePropertyChanged("BOOKING_IN_PERIOD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CRT_DATE {
            get {
                return this.CRT_DATEField;
            }
            set {
                if ((this.CRT_DATEField.Equals(value) != true)) {
                    this.CRT_DATEField = value;
                    this.RaisePropertyChanged("CRT_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRT_NAME {
            get {
                return this.CRT_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.CRT_NAMEField, value) != true)) {
                    this.CRT_NAMEField = value;
                    this.RaisePropertyChanged("CRT_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRT_STAFF {
            get {
                return this.CRT_STAFFField;
            }
            set {
                if ((object.ReferenceEquals(this.CRT_STAFFField, value) != true)) {
                    this.CRT_STAFFField = value;
                    this.RaisePropertyChanged("CRT_STAFF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUST_CODE {
            get {
                return this.CUST_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_CODEField, value) != true)) {
                    this.CUST_CODEField = value;
                    this.RaisePropertyChanged("CUST_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUST_COST {
            get {
                return this.CUST_COSTField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_COSTField, value) != true)) {
                    this.CUST_COSTField = value;
                    this.RaisePropertyChanged("CUST_COST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUST_ORD_NO {
            get {
                return this.CUST_ORD_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_ORD_NOField, value) != true)) {
                    this.CUST_ORD_NOField = value;
                    this.RaisePropertyChanged("CUST_ORD_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DC_CODE {
            get {
                return this.DC_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.DC_CODEField, value) != true)) {
                    this.DC_CODEField = value;
                    this.RaisePropertyChanged("DC_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DC_NAME {
            get {
                return this.DC_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.DC_NAMEField, value) != true)) {
                    this.DC_NAMEField = value;
                    this.RaisePropertyChanged("DC_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DELIVER_DATE {
            get {
                return this.DELIVER_DATEField;
            }
            set {
                if ((this.DELIVER_DATEField.Equals(value) != true)) {
                    this.DELIVER_DATEField = value;
                    this.RaisePropertyChanged("DELIVER_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EDI_FLAG {
            get {
                return this.EDI_FLAGField;
            }
            set {
                if ((object.ReferenceEquals(this.EDI_FLAGField, value) != true)) {
                    this.EDI_FLAGField = value;
                    this.RaisePropertyChanged("EDI_FLAG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FAST_PASS_TYPE {
            get {
                return this.FAST_PASS_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.FAST_PASS_TYPEField, value) != true)) {
                    this.FAST_PASS_TYPEField = value;
                    this.RaisePropertyChanged("FAST_PASS_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GUP_CODE {
            get {
                return this.GUP_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.GUP_CODEField, value) != true)) {
                    this.GUP_CODEField = value;
                    this.RaisePropertyChanged("GUP_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MEMO {
            get {
                return this.MEMOField;
            }
            set {
                if ((object.ReferenceEquals(this.MEMOField, value) != true)) {
                    this.MEMOField = value;
                    this.RaisePropertyChanged("MEMO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ORD_PROP {
            get {
                return this.ORD_PROPField;
            }
            set {
                if ((object.ReferenceEquals(this.ORD_PROPField, value) != true)) {
                    this.ORD_PROPField = value;
                    this.RaisePropertyChanged("ORD_PROP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SHOP_DATE {
            get {
                return this.SHOP_DATEField;
            }
            set {
                if ((this.SHOP_DATEField.Equals(value) != true)) {
                    this.SHOP_DATEField = value;
                    this.RaisePropertyChanged("SHOP_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SHOP_NO {
            get {
                return this.SHOP_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.SHOP_NOField, value) != true)) {
                    this.SHOP_NOField = value;
                    this.RaisePropertyChanged("SHOP_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SOURCE_NAME {
            get {
                return this.SOURCE_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.SOURCE_NAMEField, value) != true)) {
                    this.SOURCE_NAMEField = value;
                    this.RaisePropertyChanged("SOURCE_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SOURCE_NO {
            get {
                return this.SOURCE_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.SOURCE_NOField, value) != true)) {
                    this.SOURCE_NOField = value;
                    this.RaisePropertyChanged("SOURCE_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SOURCE_TYPE {
            get {
                return this.SOURCE_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.SOURCE_TYPEField, value) != true)) {
                    this.SOURCE_TYPEField = value;
                    this.RaisePropertyChanged("SOURCE_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STATUS {
            get {
                return this.STATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.STATUSField, value) != true)) {
                    this.STATUSField = value;
                    this.RaisePropertyChanged("STATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STATUSNAME {
            get {
                return this.STATUSNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.STATUSNAMEField, value) != true)) {
                    this.STATUSNAMEField = value;
                    this.RaisePropertyChanged("STATUSNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime STOCK_DATE {
            get {
                return this.STOCK_DATEField;
            }
            set {
                if ((this.STOCK_DATEField.Equals(value) != true)) {
                    this.STOCK_DATEField = value;
                    this.RaisePropertyChanged("STOCK_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STOCK_NO {
            get {
                return this.STOCK_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.STOCK_NOField, value) != true)) {
                    this.STOCK_NOField = value;
                    this.RaisePropertyChanged("STOCK_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UPD_DATE {
            get {
                return this.UPD_DATEField;
            }
            set {
                if ((this.UPD_DATEField.Equals(value) != true)) {
                    this.UPD_DATEField = value;
                    this.RaisePropertyChanged("UPD_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPD_NAME {
            get {
                return this.UPD_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.UPD_NAMEField, value) != true)) {
                    this.UPD_NAMEField = value;
                    this.RaisePropertyChanged("UPD_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPD_STAFF {
            get {
                return this.UPD_STAFFField;
            }
            set {
                if ((object.ReferenceEquals(this.UPD_STAFFField, value) != true)) {
                    this.UPD_STAFFField = value;
                    this.RaisePropertyChanged("UPD_STAFF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VNR_ADDRESS {
            get {
                return this.VNR_ADDRESSField;
            }
            set {
                if ((object.ReferenceEquals(this.VNR_ADDRESSField, value) != true)) {
                    this.VNR_ADDRESSField = value;
                    this.RaisePropertyChanged("VNR_ADDRESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VNR_CODE {
            get {
                return this.VNR_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.VNR_CODEField, value) != true)) {
                    this.VNR_CODEField = value;
                    this.RaisePropertyChanged("VNR_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VNR_NAME {
            get {
                return this.VNR_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.VNR_NAMEField, value) != true)) {
                    this.VNR_NAMEField = value;
                    this.RaisePropertyChanged("VNR_NAME");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="F010202Data", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class F010202Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CUST_CODEk__BackingFieldField;
        
        private string CUST_ORD_NOk__BackingFieldField;
        
        private string ChangeFlagk__BackingFieldField;
        
        private string DC_CODEk__BackingFieldField;
        
        private string EAN_CODE1k__BackingFieldField;
        
        private string EAN_CODE2k__BackingFieldField;
        
        private string GUP_CODEk__BackingFieldField;
        
        private string ITEM_CODEk__BackingFieldField;
        
        private string ITEM_COLORk__BackingFieldField;
        
        private string ITEM_NAMEk__BackingFieldField;
        
        private string ITEM_SIZEk__BackingFieldField;
        
        private string ITEM_SPECk__BackingFieldField;
        
        private string MAKE_NOk__BackingFieldField;
        
        private int ROWNUMk__BackingFieldField;
        
        private string STOCK_NOk__BackingFieldField;
        
        private int STOCK_QTYk__BackingFieldField;
        
        private int STOCK_SEQk__BackingFieldField;
        
        private string UNIT_TRANSk__BackingFieldField;
        
        private System.Nullable<System.DateTime> VALI_DATEk__BackingFieldField;
        
        private string VNR_NAMEk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CUST_CODE>k__BackingField", IsRequired=true)]
        public string CUST_CODEk__BackingField {
            get {
                return this.CUST_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_CODEk__BackingFieldField, value) != true)) {
                    this.CUST_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("CUST_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CUST_ORD_NO>k__BackingField", IsRequired=true)]
        public string CUST_ORD_NOk__BackingField {
            get {
                return this.CUST_ORD_NOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_ORD_NOk__BackingFieldField, value) != true)) {
                    this.CUST_ORD_NOk__BackingFieldField = value;
                    this.RaisePropertyChanged("CUST_ORD_NOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ChangeFlag>k__BackingField", IsRequired=true)]
        public string ChangeFlagk__BackingField {
            get {
                return this.ChangeFlagk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeFlagk__BackingFieldField, value) != true)) {
                    this.ChangeFlagk__BackingFieldField = value;
                    this.RaisePropertyChanged("ChangeFlagk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DC_CODE>k__BackingField", IsRequired=true)]
        public string DC_CODEk__BackingField {
            get {
                return this.DC_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DC_CODEk__BackingFieldField, value) != true)) {
                    this.DC_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("DC_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<EAN_CODE1>k__BackingField", IsRequired=true)]
        public string EAN_CODE1k__BackingField {
            get {
                return this.EAN_CODE1k__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.EAN_CODE1k__BackingFieldField, value) != true)) {
                    this.EAN_CODE1k__BackingFieldField = value;
                    this.RaisePropertyChanged("EAN_CODE1k__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<EAN_CODE2>k__BackingField", IsRequired=true)]
        public string EAN_CODE2k__BackingField {
            get {
                return this.EAN_CODE2k__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.EAN_CODE2k__BackingFieldField, value) != true)) {
                    this.EAN_CODE2k__BackingFieldField = value;
                    this.RaisePropertyChanged("EAN_CODE2k__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<GUP_CODE>k__BackingField", IsRequired=true)]
        public string GUP_CODEk__BackingField {
            get {
                return this.GUP_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.GUP_CODEk__BackingFieldField, value) != true)) {
                    this.GUP_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("GUP_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ITEM_CODE>k__BackingField", IsRequired=true)]
        public string ITEM_CODEk__BackingField {
            get {
                return this.ITEM_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_CODEk__BackingFieldField, value) != true)) {
                    this.ITEM_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("ITEM_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ITEM_COLOR>k__BackingField", IsRequired=true)]
        public string ITEM_COLORk__BackingField {
            get {
                return this.ITEM_COLORk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_COLORk__BackingFieldField, value) != true)) {
                    this.ITEM_COLORk__BackingFieldField = value;
                    this.RaisePropertyChanged("ITEM_COLORk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ITEM_NAME>k__BackingField", IsRequired=true)]
        public string ITEM_NAMEk__BackingField {
            get {
                return this.ITEM_NAMEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_NAMEk__BackingFieldField, value) != true)) {
                    this.ITEM_NAMEk__BackingFieldField = value;
                    this.RaisePropertyChanged("ITEM_NAMEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ITEM_SIZE>k__BackingField", IsRequired=true)]
        public string ITEM_SIZEk__BackingField {
            get {
                return this.ITEM_SIZEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_SIZEk__BackingFieldField, value) != true)) {
                    this.ITEM_SIZEk__BackingFieldField = value;
                    this.RaisePropertyChanged("ITEM_SIZEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ITEM_SPEC>k__BackingField", IsRequired=true)]
        public string ITEM_SPECk__BackingField {
            get {
                return this.ITEM_SPECk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_SPECk__BackingFieldField, value) != true)) {
                    this.ITEM_SPECk__BackingFieldField = value;
                    this.RaisePropertyChanged("ITEM_SPECk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MAKE_NO>k__BackingField", IsRequired=true)]
        public string MAKE_NOk__BackingField {
            get {
                return this.MAKE_NOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.MAKE_NOk__BackingFieldField, value) != true)) {
                    this.MAKE_NOk__BackingFieldField = value;
                    this.RaisePropertyChanged("MAKE_NOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ROWNUM>k__BackingField", IsRequired=true)]
        public int ROWNUMk__BackingField {
            get {
                return this.ROWNUMk__BackingFieldField;
            }
            set {
                if ((this.ROWNUMk__BackingFieldField.Equals(value) != true)) {
                    this.ROWNUMk__BackingFieldField = value;
                    this.RaisePropertyChanged("ROWNUMk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<STOCK_NO>k__BackingField", IsRequired=true)]
        public string STOCK_NOk__BackingField {
            get {
                return this.STOCK_NOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.STOCK_NOk__BackingFieldField, value) != true)) {
                    this.STOCK_NOk__BackingFieldField = value;
                    this.RaisePropertyChanged("STOCK_NOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<STOCK_QTY>k__BackingField", IsRequired=true)]
        public int STOCK_QTYk__BackingField {
            get {
                return this.STOCK_QTYk__BackingFieldField;
            }
            set {
                if ((this.STOCK_QTYk__BackingFieldField.Equals(value) != true)) {
                    this.STOCK_QTYk__BackingFieldField = value;
                    this.RaisePropertyChanged("STOCK_QTYk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<STOCK_SEQ>k__BackingField", IsRequired=true)]
        public int STOCK_SEQk__BackingField {
            get {
                return this.STOCK_SEQk__BackingFieldField;
            }
            set {
                if ((this.STOCK_SEQk__BackingFieldField.Equals(value) != true)) {
                    this.STOCK_SEQk__BackingFieldField = value;
                    this.RaisePropertyChanged("STOCK_SEQk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UNIT_TRANS>k__BackingField", IsRequired=true)]
        public string UNIT_TRANSk__BackingField {
            get {
                return this.UNIT_TRANSk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UNIT_TRANSk__BackingFieldField, value) != true)) {
                    this.UNIT_TRANSk__BackingFieldField = value;
                    this.RaisePropertyChanged("UNIT_TRANSk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<VALI_DATE>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> VALI_DATEk__BackingField {
            get {
                return this.VALI_DATEk__BackingFieldField;
            }
            set {
                if ((this.VALI_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.VALI_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("VALI_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<VNR_NAME>k__BackingField", IsRequired=true)]
        public string VNR_NAMEk__BackingField {
            get {
                return this.VNR_NAMEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.VNR_NAMEk__BackingFieldField, value) != true)) {
                    this.VNR_NAMEk__BackingFieldField = value;
                    this.RaisePropertyChanged("VNR_NAMEk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BarcodeData", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class BarcodeData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wms3pl.WpfClient.ExDataServices.P01WcfService.BarcodeType BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wms3pl.WpfClient.ExDataServices.P01WcfService.BarcodeType Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((this.BarcodeField.Equals(value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BarcodeText {
            get {
                return this.BarcodeTextField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeTextField, value) != true)) {
                    this.BarcodeTextField = value;
                    this.RaisePropertyChanged("BarcodeText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BarcodeType", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Common.Enums")]
    public enum BarcodeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BatchNo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BoxSerial = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CaseNo = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SerialNo = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerialNoResult", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class SerialNoResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatchNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoxSerailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CheckedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CombinNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentlyStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PukField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SEQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string boxCtrlNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string palletCtrlNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatchNo {
            get {
                return this.BatchNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchNoField, value) != true)) {
                    this.BatchNoField = value;
                    this.RaisePropertyChanged("BatchNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BoxSerail {
            get {
                return this.BoxSerailField;
            }
            set {
                if ((object.ReferenceEquals(this.BoxSerailField, value) != true)) {
                    this.BoxSerailField = value;
                    this.RaisePropertyChanged("BoxSerail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseNo {
            get {
                return this.CaseNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseNoField, value) != true)) {
                    this.CaseNoField = value;
                    this.RaisePropertyChanged("CaseNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellNum {
            get {
                return this.CellNumField;
            }
            set {
                if ((object.ReferenceEquals(this.CellNumField, value) != true)) {
                    this.CellNumField = value;
                    this.RaisePropertyChanged("CellNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Checked {
            get {
                return this.CheckedField;
            }
            set {
                if ((this.CheckedField.Equals(value) != true)) {
                    this.CheckedField = value;
                    this.RaisePropertyChanged("Checked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CombinNo {
            get {
                return this.CombinNoField;
            }
            set {
                if ((this.CombinNoField.Equals(value) != true)) {
                    this.CombinNoField = value;
                    this.RaisePropertyChanged("CombinNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentlyStatus {
            get {
                return this.CurrentlyStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentlyStatusField, value) != true)) {
                    this.CurrentlyStatusField = value;
                    this.RaisePropertyChanged("CurrentlyStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemColor {
            get {
                return this.ItemColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemColorField, value) != true)) {
                    this.ItemColorField = value;
                    this.RaisePropertyChanged("ItemColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemSize {
            get {
                return this.ItemSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemSizeField, value) != true)) {
                    this.ItemSizeField = value;
                    this.RaisePropertyChanged("ItemSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeNo {
            get {
                return this.MakeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeNoField, value) != true)) {
                    this.MakeNoField = value;
                    this.RaisePropertyChanged("MakeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Puk {
            get {
                return this.PukField;
            }
            set {
                if ((object.ReferenceEquals(this.PukField, value) != true)) {
                    this.PukField = value;
                    this.RaisePropertyChanged("Puk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SEQ {
            get {
                return this.SEQField;
            }
            set {
                if ((this.SEQField.Equals(value) != true)) {
                    this.SEQField = value;
                    this.RaisePropertyChanged("SEQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNo {
            get {
                return this.SerialNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNoField, value) != true)) {
                    this.SerialNoField = value;
                    this.RaisePropertyChanged("SerialNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string boxCtrlNo {
            get {
                return this.boxCtrlNoField;
            }
            set {
                if ((object.ReferenceEquals(this.boxCtrlNoField, value) != true)) {
                    this.boxCtrlNoField = value;
                    this.RaisePropertyChanged("boxCtrlNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string palletCtrlNo {
            get {
                return this.palletCtrlNoField;
            }
            set {
                if ((object.ReferenceEquals(this.palletCtrlNoField, value) != true)) {
                    this.palletCtrlNoField = value;
                    this.RaisePropertyChanged("palletCtrlNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="F010201ImportData", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class F010201ImportData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BOOKING_IN_PERIODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FAST_PASS_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITEM_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITEM_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MAKE_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int STOCK_QTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> VALI_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VNR_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VNR_NAMEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BOOKING_IN_PERIOD {
            get {
                return this.BOOKING_IN_PERIODField;
            }
            set {
                if ((object.ReferenceEquals(this.BOOKING_IN_PERIODField, value) != true)) {
                    this.BOOKING_IN_PERIODField = value;
                    this.RaisePropertyChanged("BOOKING_IN_PERIOD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FAST_PASS_TYPE {
            get {
                return this.FAST_PASS_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.FAST_PASS_TYPEField, value) != true)) {
                    this.FAST_PASS_TYPEField = value;
                    this.RaisePropertyChanged("FAST_PASS_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITEM_CODE {
            get {
                return this.ITEM_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_CODEField, value) != true)) {
                    this.ITEM_CODEField = value;
                    this.RaisePropertyChanged("ITEM_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITEM_NAME {
            get {
                return this.ITEM_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_NAMEField, value) != true)) {
                    this.ITEM_NAMEField = value;
                    this.RaisePropertyChanged("ITEM_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MAKE_NO {
            get {
                return this.MAKE_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.MAKE_NOField, value) != true)) {
                    this.MAKE_NOField = value;
                    this.RaisePropertyChanged("MAKE_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_NO {
            get {
                return this.PO_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_NOField, value) != true)) {
                    this.PO_NOField = value;
                    this.RaisePropertyChanged("PO_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int STOCK_QTY {
            get {
                return this.STOCK_QTYField;
            }
            set {
                if ((this.STOCK_QTYField.Equals(value) != true)) {
                    this.STOCK_QTYField = value;
                    this.RaisePropertyChanged("STOCK_QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> VALI_DATE {
            get {
                return this.VALI_DATEField;
            }
            set {
                if ((this.VALI_DATEField.Equals(value) != true)) {
                    this.VALI_DATEField = value;
                    this.RaisePropertyChanged("VALI_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VNR_CODE {
            get {
                return this.VNR_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.VNR_CODEField, value) != true)) {
                    this.VNR_CODEField = value;
                    this.RaisePropertyChanged("VNR_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VNR_NAME {
            get {
                return this.VNR_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.VNR_NAMEField, value) != true)) {
                    this.VNR_NAMEField = value;
                    this.RaisePropertyChanged("VNR_NAME");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="P01WcfService.P01WcfService")]
    public interface P01WcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/InsertP010101", ReplyAction="http://tempuri.org/P01WcfService/InsertP010101Response")]
        Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult InsertP010101(Wms3pl.WpfClient.ExDataServices.P01WcfService.F010101Data shopData, Wms3pl.WpfClient.ExDataServices.P01WcfService.F010102Data[] shopDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/InsertP010101", ReplyAction="http://tempuri.org/P01WcfService/InsertP010101Response")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult> InsertP010101Async(Wms3pl.WpfClient.ExDataServices.P01WcfService.F010101Data shopData, Wms3pl.WpfClient.ExDataServices.P01WcfService.F010102Data[] shopDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/UpdateP010101", ReplyAction="http://tempuri.org/P01WcfService/UpdateP010101Response")]
        Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult UpdateP010101(Wms3pl.WpfClient.ExDataServices.P01WcfService.F010101Data shopData, Wms3pl.WpfClient.ExDataServices.P01WcfService.F010102Data[] shopDetails, bool isApproved);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/UpdateP010101", ReplyAction="http://tempuri.org/P01WcfService/UpdateP010101Response")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult> UpdateP010101Async(Wms3pl.WpfClient.ExDataServices.P01WcfService.F010101Data shopData, Wms3pl.WpfClient.ExDataServices.P01WcfService.F010102Data[] shopDetails, bool isApproved);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/InsertOrUpdateP010201", ReplyAction="http://tempuri.org/P01WcfService/InsertOrUpdateP010201Response")]
        Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult InsertOrUpdateP010201(Wms3pl.WpfClient.ExDataServices.P01WcfService.F010201Data f010201Data, Wms3pl.WpfClient.ExDataServices.P01WcfService.F010202Data[] f010202Datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/InsertOrUpdateP010201", ReplyAction="http://tempuri.org/P01WcfService/InsertOrUpdateP010201Response")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult> InsertOrUpdateP010201Async(Wms3pl.WpfClient.ExDataServices.P01WcfService.F010201Data f010201Data, Wms3pl.WpfClient.ExDataServices.P01WcfService.F010202Data[] f010202Datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/BarcodeInspection", ReplyAction="http://tempuri.org/P01WcfService/BarcodeInspectionResponse")]
        Wms3pl.WpfClient.ExDataServices.P01WcfService.BarcodeData BarcodeInspection(string gupCode, string custCode, string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/BarcodeInspection", ReplyAction="http://tempuri.org/P01WcfService/BarcodeInspectionResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P01WcfService.BarcodeData> BarcodeInspectionAsync(string gupCode, string custCode, string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/GetItemCodeBySerialNo", ReplyAction="http://tempuri.org/P01WcfService/GetItemCodeBySerialNoResponse")]
        string GetItemCodeBySerialNo(string dcCode, string gupCode, string custCode, string serialNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/GetItemCodeBySerialNo", ReplyAction="http://tempuri.org/P01WcfService/GetItemCodeBySerialNoResponse")]
        System.Threading.Tasks.Task<string> GetItemCodeBySerialNoAsync(string dcCode, string gupCode, string custCode, string serialNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/SerialNoStatusCheckAll", ReplyAction="http://tempuri.org/P01WcfService/SerialNoStatusCheckAllResponse")]
        Wms3pl.WpfClient.ExDataServices.P01WcfService.SerialNoResult SerialNoStatusCheckAll(string gupCode, string custCode, string itemCode, string serialNo, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/SerialNoStatusCheckAll", ReplyAction="http://tempuri.org/P01WcfService/SerialNoStatusCheckAllResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P01WcfService.SerialNoResult> SerialNoStatusCheckAllAsync(string gupCode, string custCode, string itemCode, string serialNo, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/SerialNoStatusCheck", ReplyAction="http://tempuri.org/P01WcfService/SerialNoStatusCheckResponse")]
        Wms3pl.WpfClient.ExDataServices.P01WcfService.SerialNoResult SerialNoStatusCheck(string gupCode, string custCode, string serialNo, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/SerialNoStatusCheck", ReplyAction="http://tempuri.org/P01WcfService/SerialNoStatusCheckResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P01WcfService.SerialNoResult> SerialNoStatusCheckAsync(string gupCode, string custCode, string serialNo, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/ImportF10201Data", ReplyAction="http://tempuri.org/P01WcfService/ImportF10201DataResponse")]
        Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult ImportF10201Data(string dcCode, string gupCode, string custCode, string fileName, Wms3pl.WpfClient.ExDataServices.P01WcfService.F010201ImportData[] importData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/ImportF10201Data", ReplyAction="http://tempuri.org/P01WcfService/ImportF10201DataResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult> ImportF10201DataAsync(string dcCode, string gupCode, string custCode, string fileName, Wms3pl.WpfClient.ExDataServices.P01WcfService.F010201ImportData[] importData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/CountPallet", ReplyAction="http://tempuri.org/P01WcfService/CountPalletResponse")]
        Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult CountPallet(string dcCode, string gupCode, string custCode, string stockNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/CountPallet", ReplyAction="http://tempuri.org/P01WcfService/CountPalletResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult> CountPalletAsync(string dcCode, string gupCode, string custCode, string stockNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/GetInboundCnt", ReplyAction="http://tempuri.org/P01WcfService/GetInboundCntResponse")]
        int GetInboundCnt(string dcCode, string gupCode, string custCode, string[] stockNos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P01WcfService/GetInboundCnt", ReplyAction="http://tempuri.org/P01WcfService/GetInboundCntResponse")]
        System.Threading.Tasks.Task<int> GetInboundCntAsync(string dcCode, string gupCode, string custCode, string[] stockNos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface P01WcfServiceChannel : Wms3pl.WpfClient.ExDataServices.P01WcfService.P01WcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class P01WcfServiceClient : System.ServiceModel.ClientBase<Wms3pl.WpfClient.ExDataServices.P01WcfService.P01WcfService>, Wms3pl.WpfClient.ExDataServices.P01WcfService.P01WcfService {
        
        public P01WcfServiceClient() {
        }
        
        public P01WcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public P01WcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public P01WcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public P01WcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult InsertP010101(Wms3pl.WpfClient.ExDataServices.P01WcfService.F010101Data shopData, Wms3pl.WpfClient.ExDataServices.P01WcfService.F010102Data[] shopDetails) {
            return base.Channel.InsertP010101(shopData, shopDetails);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult> InsertP010101Async(Wms3pl.WpfClient.ExDataServices.P01WcfService.F010101Data shopData, Wms3pl.WpfClient.ExDataServices.P01WcfService.F010102Data[] shopDetails) {
            return base.Channel.InsertP010101Async(shopData, shopDetails);
        }
        
        public Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult UpdateP010101(Wms3pl.WpfClient.ExDataServices.P01WcfService.F010101Data shopData, Wms3pl.WpfClient.ExDataServices.P01WcfService.F010102Data[] shopDetails, bool isApproved) {
            return base.Channel.UpdateP010101(shopData, shopDetails, isApproved);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult> UpdateP010101Async(Wms3pl.WpfClient.ExDataServices.P01WcfService.F010101Data shopData, Wms3pl.WpfClient.ExDataServices.P01WcfService.F010102Data[] shopDetails, bool isApproved) {
            return base.Channel.UpdateP010101Async(shopData, shopDetails, isApproved);
        }
        
        public Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult InsertOrUpdateP010201(Wms3pl.WpfClient.ExDataServices.P01WcfService.F010201Data f010201Data, Wms3pl.WpfClient.ExDataServices.P01WcfService.F010202Data[] f010202Datas) {
            return base.Channel.InsertOrUpdateP010201(f010201Data, f010202Datas);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult> InsertOrUpdateP010201Async(Wms3pl.WpfClient.ExDataServices.P01WcfService.F010201Data f010201Data, Wms3pl.WpfClient.ExDataServices.P01WcfService.F010202Data[] f010202Datas) {
            return base.Channel.InsertOrUpdateP010201Async(f010201Data, f010202Datas);
        }
        
        public Wms3pl.WpfClient.ExDataServices.P01WcfService.BarcodeData BarcodeInspection(string gupCode, string custCode, string barcode) {
            return base.Channel.BarcodeInspection(gupCode, custCode, barcode);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P01WcfService.BarcodeData> BarcodeInspectionAsync(string gupCode, string custCode, string barcode) {
            return base.Channel.BarcodeInspectionAsync(gupCode, custCode, barcode);
        }
        
        public string GetItemCodeBySerialNo(string dcCode, string gupCode, string custCode, string serialNo) {
            return base.Channel.GetItemCodeBySerialNo(dcCode, gupCode, custCode, serialNo);
        }
        
        public System.Threading.Tasks.Task<string> GetItemCodeBySerialNoAsync(string dcCode, string gupCode, string custCode, string serialNo) {
            return base.Channel.GetItemCodeBySerialNoAsync(dcCode, gupCode, custCode, serialNo);
        }
        
        public Wms3pl.WpfClient.ExDataServices.P01WcfService.SerialNoResult SerialNoStatusCheckAll(string gupCode, string custCode, string itemCode, string serialNo, string status) {
            return base.Channel.SerialNoStatusCheckAll(gupCode, custCode, itemCode, serialNo, status);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P01WcfService.SerialNoResult> SerialNoStatusCheckAllAsync(string gupCode, string custCode, string itemCode, string serialNo, string status) {
            return base.Channel.SerialNoStatusCheckAllAsync(gupCode, custCode, itemCode, serialNo, status);
        }
        
        public Wms3pl.WpfClient.ExDataServices.P01WcfService.SerialNoResult SerialNoStatusCheck(string gupCode, string custCode, string serialNo, string status) {
            return base.Channel.SerialNoStatusCheck(gupCode, custCode, serialNo, status);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P01WcfService.SerialNoResult> SerialNoStatusCheckAsync(string gupCode, string custCode, string serialNo, string status) {
            return base.Channel.SerialNoStatusCheckAsync(gupCode, custCode, serialNo, status);
        }
        
        public Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult ImportF10201Data(string dcCode, string gupCode, string custCode, string fileName, Wms3pl.WpfClient.ExDataServices.P01WcfService.F010201ImportData[] importData) {
            return base.Channel.ImportF10201Data(dcCode, gupCode, custCode, fileName, importData);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult> ImportF10201DataAsync(string dcCode, string gupCode, string custCode, string fileName, Wms3pl.WpfClient.ExDataServices.P01WcfService.F010201ImportData[] importData) {
            return base.Channel.ImportF10201DataAsync(dcCode, gupCode, custCode, fileName, importData);
        }
        
        public Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult CountPallet(string dcCode, string gupCode, string custCode, string stockNo) {
            return base.Channel.CountPallet(dcCode, gupCode, custCode, stockNo);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P01WcfService.ExecuteResult> CountPalletAsync(string dcCode, string gupCode, string custCode, string stockNo) {
            return base.Channel.CountPalletAsync(dcCode, gupCode, custCode, stockNo);
        }
        
        public int GetInboundCnt(string dcCode, string gupCode, string custCode, string[] stockNos) {
            return base.Channel.GetInboundCnt(dcCode, gupCode, custCode, stockNos);
        }
        
        public System.Threading.Tasks.Task<int> GetInboundCntAsync(string dcCode, string gupCode, string custCode, string[] stockNos) {
            return base.Channel.GetInboundCntAsync(dcCode, gupCode, custCode, stockNos);
        }
    }
}
