//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms3pl.WpfClient.ExDataServices.ExportWcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExportResultReq", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.ApiEntities")]
    [System.SerializableAttribute()]
    public partial class ExportResultReq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DcCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GupCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScheduleNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustCode {
            get {
                return this.CustCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustCodeField, value) != true)) {
                    this.CustCodeField = value;
                    this.RaisePropertyChanged("CustCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DcCode {
            get {
                return this.DcCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DcCodeField, value) != true)) {
                    this.DcCodeField = value;
                    this.RaisePropertyChanged("DcCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GupCode {
            get {
                return this.GupCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GupCodeField, value) != true)) {
                    this.GupCodeField = value;
                    this.RaisePropertyChanged("GupCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScheduleNo {
            get {
                return this.ScheduleNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ScheduleNoField, value) != true)) {
                    this.ScheduleNoField = value;
                    this.RaisePropertyChanged("ScheduleNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResult", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.ApiEntities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq))]
    public partial class ApiResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FailureCntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InsertCntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SuccessCntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UpdateCntField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FailureCnt {
            get {
                return this.FailureCntField;
            }
            set {
                if ((this.FailureCntField.Equals(value) != true)) {
                    this.FailureCntField = value;
                    this.RaisePropertyChanged("FailureCnt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InsertCnt {
            get {
                return this.InsertCntField;
            }
            set {
                if ((this.InsertCntField.Equals(value) != true)) {
                    this.InsertCntField = value;
                    this.RaisePropertyChanged("InsertCnt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessed {
            get {
                return this.IsSuccessedField;
            }
            set {
                if ((this.IsSuccessedField.Equals(value) != true)) {
                    this.IsSuccessedField = value;
                    this.RaisePropertyChanged("IsSuccessed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsgCode {
            get {
                return this.MsgCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgCodeField, value) != true)) {
                    this.MsgCodeField = value;
                    this.RaisePropertyChanged("MsgCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsgContent {
            get {
                return this.MsgContentField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgContentField, value) != true)) {
                    this.MsgContentField = value;
                    this.RaisePropertyChanged("MsgContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SuccessCnt {
            get {
                return this.SuccessCntField;
            }
            set {
                if ((this.SuccessCntField.Equals(value) != true)) {
                    this.SuccessCntField = value;
                    this.RaisePropertyChanged("SuccessCnt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCnt {
            get {
                return this.TotalCntField;
            }
            set {
                if ((this.TotalCntField.Equals(value) != true)) {
                    this.TotalCntField = value;
                    this.RaisePropertyChanged("TotalCnt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdateCnt {
            get {
                return this.UpdateCntField;
            }
            set {
                if ((this.UpdateCntField.Equals(value) != true)) {
                    this.UpdateCntField = value;
                    this.RaisePropertyChanged("UpdateCnt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExportWcfService.ExportWcfService")]
    public interface ExportWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportWcfService/ExportWarehouseInResults", ReplyAction="http://tempuri.org/ExportWcfService/ExportWarehouseInResultsResponse")]
        Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult ExportWarehouseInResults(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportWcfService/ExportWarehouseInResults", ReplyAction="http://tempuri.org/ExportWcfService/ExportWarehouseInResultsResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult> ExportWarehouseInResultsAsync(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportWcfService/ExportOrderResults", ReplyAction="http://tempuri.org/ExportWcfService/ExportOrderResultsResponse")]
        Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult ExportOrderResults(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportWcfService/ExportOrderResults", ReplyAction="http://tempuri.org/ExportWcfService/ExportOrderResultsResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult> ExportOrderResultsAsync(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportWcfService/ExportVendorReturnResults", ReplyAction="http://tempuri.org/ExportWcfService/ExportVendorReturnResultsResponse")]
        Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult ExportVendorReturnResults(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportWcfService/ExportVendorReturnResults", ReplyAction="http://tempuri.org/ExportWcfService/ExportVendorReturnResultsResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult> ExportVendorReturnResultsAsync(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportWcfService/ExpStockAlertResults", ReplyAction="http://tempuri.org/ExportWcfService/ExpStockAlertResultsResponse")]
        Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult ExpStockAlertResults(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportWcfService/ExpStockAlertResults", ReplyAction="http://tempuri.org/ExportWcfService/ExpStockAlertResultsResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult> ExpStockAlertResultsAsync(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportWcfService/ExportHomeDeliveryResults", ReplyAction="http://tempuri.org/ExportWcfService/ExportHomeDeliveryResultsResponse")]
        Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult ExportHomeDeliveryResults(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportWcfService/ExportHomeDeliveryResults", ReplyAction="http://tempuri.org/ExportWcfService/ExportHomeDeliveryResultsResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult> ExportHomeDeliveryResultsAsync(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportWcfService/ExportStockMovementResults", ReplyAction="http://tempuri.org/ExportWcfService/ExportStockMovementResultsResponse")]
        Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult ExportStockMovementResults(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportWcfService/ExportStockMovementResults", ReplyAction="http://tempuri.org/ExportWcfService/ExportStockMovementResultsResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult> ExportStockMovementResultsAsync(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportWcfService/ExportSysErrorNotifyResults", ReplyAction="http://tempuri.org/ExportWcfService/ExportSysErrorNotifyResultsResponse")]
        Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult ExportSysErrorNotifyResults(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportWcfService/ExportSysErrorNotifyResults", ReplyAction="http://tempuri.org/ExportWcfService/ExportSysErrorNotifyResultsResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult> ExportSysErrorNotifyResultsAsync(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExportWcfServiceChannel : Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExportWcfServiceClient : System.ServiceModel.ClientBase<Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportWcfService>, Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportWcfService {
        
        public ExportWcfServiceClient() {
        }
        
        public ExportWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExportWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult ExportWarehouseInResults(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req) {
            return base.Channel.ExportWarehouseInResults(req);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult> ExportWarehouseInResultsAsync(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req) {
            return base.Channel.ExportWarehouseInResultsAsync(req);
        }
        
        public Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult ExportOrderResults(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req) {
            return base.Channel.ExportOrderResults(req);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult> ExportOrderResultsAsync(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req) {
            return base.Channel.ExportOrderResultsAsync(req);
        }
        
        public Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult ExportVendorReturnResults(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req) {
            return base.Channel.ExportVendorReturnResults(req);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult> ExportVendorReturnResultsAsync(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req) {
            return base.Channel.ExportVendorReturnResultsAsync(req);
        }
        
        public Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult ExpStockAlertResults(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req) {
            return base.Channel.ExpStockAlertResults(req);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult> ExpStockAlertResultsAsync(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req) {
            return base.Channel.ExpStockAlertResultsAsync(req);
        }
        
        public Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult ExportHomeDeliveryResults(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req) {
            return base.Channel.ExportHomeDeliveryResults(req);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult> ExportHomeDeliveryResultsAsync(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req) {
            return base.Channel.ExportHomeDeliveryResultsAsync(req);
        }
        
        public Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult ExportStockMovementResults(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req) {
            return base.Channel.ExportStockMovementResults(req);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult> ExportStockMovementResultsAsync(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req) {
            return base.Channel.ExportStockMovementResultsAsync(req);
        }
        
        public Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult ExportSysErrorNotifyResults(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req) {
            return base.Channel.ExportSysErrorNotifyResults(req);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.ExportWcfService.ApiResult> ExportSysErrorNotifyResultsAsync(Wms3pl.WpfClient.ExDataServices.ExportWcfService.ExportResultReq req) {
            return base.Channel.ExportSysErrorNotifyResultsAsync(req);
        }
    }
}
