//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms3pl.WpfClient.P14.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms3pl.WpfClient.P14.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 新增明細 的當地語系化字串。
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點名稱 的當地語系化字串。
        /// </summary>
        public static string AddOrEditInventoryName {
            get {
                return ResourceManager.GetString("AddOrEditInventoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點倉別 的當地語系化字串。
        /// </summary>
        public static string AddOrEditWareHouseId {
            get {
                return ResourceManager.GetString("AddOrEditWareHouseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 調整狀態 的當地語系化字串。
        /// </summary>
        public static string AdjustStatus {
            get {
                return ResourceManager.GetString("AdjustStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AGV盤點狀態 的當地語系化字串。
        /// </summary>
        public static string AGV_STATUS_DESC {
            get {
                return ResourceManager.GetString("AGV_STATUS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 全部有差異商品 的當地語系化字串。
        /// </summary>
        public static string AllDifferenceProduct {
            get {
                return ResourceManager.GetString("AllDifferenceProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲區 的當地語系化字串。
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲區名稱 的當地語系化字串。
        /// </summary>
        public static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自動倉庫存數量 的當地語系化字串。
        /// </summary>
        public static string AutomaticWarehouseQty {
            get {
                return ResourceManager.GetString("AutomaticWarehouseQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 箱號 的當地語系化字串。
        /// </summary>
        public static string BOX_CTRL_NO {
            get {
                return ResourceManager.GetString("BOX_CTRL_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通道起 的當地語系化字串。
        /// </summary>
        public static string CHANNEL_BEGIN {
            get {
                return ResourceManager.GetString("CHANNEL_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通道迄 的當地語系化字串。
        /// </summary>
        public static string CHANNEL_END {
            get {
                return ResourceManager.GetString("CHANNEL_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點工具 的當地語系化字串。
        /// </summary>
        public static string CHECK_TOOL_DESC {
            get {
                return ResourceManager.GetString("CHECK_TOOL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點工具 的當地語系化字串。
        /// </summary>
        public static string CheckTool {
            get {
                return ResourceManager.GetString("CheckTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立時間 的當地語系化字串。
        /// </summary>
        public static string CRT_DATE {
            get {
                return ResourceManager.GetString("CRT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前關帳點： 的當地語系化字串。
        /// </summary>
        public static string CurrentClosePoint {
            get {
                return ResourceManager.GetString("CurrentClosePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 循環盤點第 的當地語系化字串。
        /// </summary>
        public static string CYCLE_TIMES {
            get {
                return ResourceManager.GetString("CYCLE_TIMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除明細 的當地語系化字串。
        /// </summary>
        public static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢明細結果 的當地語系化字串。
        /// </summary>
        public static string DetailRecords {
            get {
                return ResourceManager.GetString("DetailRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點差異數(B-A) 的當地語系化字串。
        /// </summary>
        public static string DIFF_QTY {
            get {
                return ResourceManager.GetString("DIFF_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WMS庫存數量 的當地語系化字串。
        /// </summary>
        public static string EditQty {
            get {
                return ResourceManager.GetString("EditQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 入庫日期 的當地語系化字串。
        /// </summary>
        public static string ENTER_DATE {
            get {
                return ResourceManager.GetString("ENTER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 入庫日 的當地語系化字串。
        /// </summary>
        public static string EnterDate {
            get {
                return ResourceManager.GetString("EnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Excel 盤點結果匯入 的當地語系化字串。
        /// </summary>
        public static string ExcelImportInventoryDetailItem {
            get {
                return ResourceManager.GetString("ExcelImportInventoryDetailItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Excel 匯入 的當地語系化字串。
        /// </summary>
        public static string ExcelImportItemCode {
            get {
                return ResourceManager.GetString("ExcelImportItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出盤點單明細 的當地語系化字串。
        /// </summary>
        public static string ExportDetailWareHouseList {
            get {
                return ResourceManager.GetString("ExportDetailWareHouseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出盤點單失敗明細 的當地語系化字串。
        /// </summary>
        public static string ExportFailDataDetail {
            get {
                return ResourceManager.GetString("ExportFailDataDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 錯誤訊息 的當地語系化字串。
        /// </summary>
        public static string FailMessage {
            get {
                return ResourceManager.GetString("FailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 費用/次 的當地語系化字串。
        /// </summary>
        public static string FEE {
            get {
                return ResourceManager.GetString("FEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 篩選條件 的當地語系化字串。
        /// </summary>
        public static string FilterCondition {
            get {
                return ResourceManager.GetString("FilterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 篩選條件一 的當地語系化字串。
        /// </summary>
        public static string First_Condition {
            get {
                return ResourceManager.GetString("First_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 初盤數 的當地語系化字串。
        /// </summary>
        public static string FIRST_QTY {
            get {
                return ResourceManager.GetString("FIRST_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 樓層起 的當地語系化字串。
        /// </summary>
        public static string FLOOR_BEGIN {
            get {
                return ResourceManager.GetString("FLOOR_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 樓層迄 的當地語系化字串。
        /// </summary>
        public static string FLOOR_END {
            get {
                return ResourceManager.GetString("FLOOR_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤盈可回沖 的當地語系化字串。
        /// </summary>
        public static string Flush_Back {
            get {
                return ResourceManager.GetString("Flush_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤盈可回沖 的當地語系化字串。
        /// </summary>
        public static string FLUSHBACK {
            get {
                return ResourceManager.GetString("FLUSHBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 初盤時間 的當地語系化字串。
        /// </summary>
        public static string FST_INVENTORY_DATE {
            get {
                return ResourceManager.GetString("FST_INVENTORY_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 初盤人員 的當地語系化字串。
        /// </summary>
        public static string FST_INVENTORY_NAME {
            get {
                return ResourceManager.GetString("FST_INVENTORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 週期 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_CYCLE {
            get {
                return ResourceManager.GetString("INVENTORY_CYCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點日期 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_DATE {
            get {
                return ResourceManager.GetString("INVENTORY_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 月 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_MON {
            get {
                return ResourceManager.GetString("INVENTORY_MON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點人員 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_NAME {
            get {
                return ResourceManager.GetString("INVENTORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點單號 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_NO {
            get {
                return ResourceManager.GetString("INVENTORY_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點時間 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_TIME {
            get {
                return ResourceManager.GetString("INVENTORY_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點類別 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_TYPE {
            get {
                return ResourceManager.GetString("INVENTORY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 年 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_YEAR {
            get {
                return ResourceManager.GetString("INVENTORY_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點結果 的當地語系化字串。
        /// </summary>
        public static string InventoryDetailItem {
            get {
                return ResourceManager.GetString("InventoryDetailItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點差異數 的當地語系化字串。
        /// </summary>
        public static string InventoryDiscrepancies {
            get {
                return ResourceManager.GetString("InventoryDiscrepancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點單產生單據 的當地語系化字串。
        /// </summary>
        public static string InventoryDoc {
            get {
                return ResourceManager.GetString("InventoryDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點商品 的當地語系化字串。
        /// </summary>
        public static string InventoryItemList {
            get {
                return ResourceManager.GetString("InventoryItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點儲位 的當地語系化字串。
        /// </summary>
        public static string InventoryLoc {
            get {
                return ResourceManager.GetString("InventoryLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點人員 的當地語系化字串。
        /// </summary>
        public static string InventoryName {
            get {
                return ResourceManager.GetString("InventoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 實際盤點數量(B) 的當地語系化字串。
        /// </summary>
        public static string InventoryQty {
            get {
                return ResourceManager.GetString("InventoryQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點時間 的當地語系化字串。
        /// </summary>
        public static string InventoryTime {
            get {
                return ResourceManager.GetString("InventoryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點庫差數 的當地語系化字串。
        /// </summary>
        public static string InventoryWarehouseDiscrepancies {
            get {
                return ResourceManager.GetString("InventoryWarehouseDiscrepancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 年/月 的當地語系化字串。
        /// </summary>
        public static string InventoryYearMonth {
            get {
                return ResourceManager.GetString("InventoryYearMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 計費 的當地語系化字串。
        /// </summary>
        public static string ISCHARGE {
            get {
                return ResourceManager.GetString("ISCHARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 指定商品： 的當地語系化字串。
        /// </summary>
        public static string IsItemCode {
            get {
                return ResourceManager.GetString("IsItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 差異數量介於 的當地語系化字串。
        /// </summary>
        public static string IsRangeProduct {
            get {
                return ResourceManager.GetString("IsRangeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        public static string IsSelected {
            get {
                return ResourceManager.GetString("IsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢明細條件 的當地語系化字串。
        /// </summary>
        public static string IsShowQueryDetailRule {
            get {
                return ResourceManager.GetString("IsShowQueryDetailRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品項總數 的當地語系化字串。
        /// </summary>
        public static string ITEM_CNT {
            get {
                return ResourceManager.GetString("ITEM_CNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品號 的當地語系化字串。
        /// </summary>
        public static string ITEM_CODE {
            get {
                return ResourceManager.GetString("ITEM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顏色 的當地語系化字串。
        /// </summary>
        public static string ITEM_COLOR {
            get {
                return ResourceManager.GetString("ITEM_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品名 的當地語系化字串。
        /// </summary>
        public static string ITEM_NAME {
            get {
                return ResourceManager.GetString("ITEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品總數 的當地語系化字串。
        /// </summary>
        public static string ITEM_QTY {
            get {
                return ResourceManager.GetString("ITEM_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尺寸 的當地語系化字串。
        /// </summary>
        public static string ITEM_SIZE {
            get {
                return ResourceManager.GetString("ITEM_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 規格 的當地語系化字串。
        /// </summary>
        public static string ITEM_SPEC {
            get {
                return ResourceManager.GetString("ITEM_SPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品號 的當地語系化字串。
        /// </summary>
        public static string ItemCode {
            get {
                return ResourceManager.GetString("ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顏色 的當地語系化字串。
        /// </summary>
        public static string ItemColor {
            get {
                return ResourceManager.GetString("ItemColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品名 的當地語系化字串。
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品項差異數 的當地語系化字串。
        /// </summary>
        public static string ITEMQTY {
            get {
                return ResourceManager.GetString("ITEMQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尺寸 的當地語系化字串。
        /// </summary>
        public static string ItemSize {
            get {
                return ResourceManager.GetString("ItemSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 規格 的當地語系化字串。
        /// </summary>
        public static string ItemSpec {
            get {
                return ResourceManager.GetString("ItemSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲位 的當地語系化字串。
        /// </summary>
        public static string Loc__Code {
            get {
                return ResourceManager.GetString("Loc__Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲位編號 的當地語系化字串。
        /// </summary>
        public static string LOC_CODE {
            get {
                return ResourceManager.GetString("LOC_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲位 的當地語系化字串。
        /// </summary>
        public static string LocCode {
            get {
                return ResourceManager.GetString("LocCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤損數 的當地語系化字串。
        /// </summary>
        public static string LOSS_QTY {
            get {
                return ResourceManager.GetString("LOSS_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 批號 的當地語系化字串。
        /// </summary>
        public static string MAKE_NO {
            get {
                return ResourceManager.GetString("MAKE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        public static string MEMO {
            get {
                return ResourceManager.GetString("MEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 錯誤儲位清單 的當地語系化字串。
        /// </summary>
        public static string P140101_ErrorLocCodeList {
            get {
                return ResourceManager.GetString("P140101_ErrorLocCodeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Excel匯入 的當地語系化字串。
        /// </summary>
        public static string P140101_ExcelImportLoc {
            get {
                return ResourceManager.GetString("P140101_ExcelImportLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料欄位錯誤! 的當地語系化字串。
        /// </summary>
        public static string P140101_ImportInventoryLocFormatError {
            get {
                return ResourceManager.GetString("P140101_ImportInventoryLocFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入資料中有{0}筆儲位不存在，{1}請確認畫面上錯誤儲位清單中{1}倉別、儲區是否正確! 的當地語系化字串。
        /// </summary>
        public static string P140101_ImportInventoryLocNotExist {
            get {
                return ResourceManager.GetString("P140101_ImportInventoryLocNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入檔案無資料 的當地語系化字串。
        /// </summary>
        public static string P140101_ImportInventoryLocNull {
            get {
                return ResourceManager.GetString("P140101_ImportInventoryLocNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲位重複{0}筆，將自動排除 的當地語系化字串。
        /// </summary>
        public static string P140101_ImportInventoryLocRepeat {
            get {
                return ResourceManager.GetString("P140101_ImportInventoryLocRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入資料重複 的當地語系化字串。
        /// </summary>
        public static string P140101_ImportRepeatData {
            get {
                return ResourceManager.GetString("P140101_ImportRepeatData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點儲位只能輸入{0}筆 的當地語系化字串。
        /// </summary>
        public static string P140101_InventoryLocLimit {
            get {
                return ResourceManager.GetString("P140101_InventoryLocLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輸入儲位長度錯誤!! 的當地語系化字串。
        /// </summary>
        public static string P140101_InventoryLocLongError {
            get {
                return ResourceManager.GetString("P140101_InventoryLocLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲位不存在，請確認倉別、儲區是否正確! 的當地語系化字串。
        /// </summary>
        public static string P140101_InventoryLocNotExist {
            get {
                return ResourceManager.GetString("P140101_InventoryLocNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點儲位必須輸入 的當地語系化字串。
        /// </summary>
        public static string P140101_InventoryLocNull {
            get {
                return ResourceManager.GetString("P140101_InventoryLocNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲位重複!! 的當地語系化字串。
        /// </summary>
        public static string P140101_InventoryLocRepeat {
            get {
                return ResourceManager.GetString("P140101_InventoryLocRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲位編號清單 的當地語系化字串。
        /// </summary>
        public static string P140101_LocCodeList {
            get {
                return ResourceManager.GetString("P140101_LocCodeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 手動輸入 的當地語系化字串。
        /// </summary>
        public static string P140101_Manual {
            get {
                return ResourceManager.GetString("P140101_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 遮罩規則 的當地語系化字串。
        /// </summary>
        public static string P140101_MaskCode {
            get {
                return ResourceManager.GetString("P140101_MaskCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇盤點儲區! 的當地語系化字串。
        /// </summary>
        public static string P140101_NotSelectedInventoryArea {
            get {
                return ResourceManager.GetString("P140101_NotSelectedInventoryArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 遮罩規則未選擇! 的當地語系化字串。
        /// </summary>
        public static string P140101_NotSelectedMask {
            get {
                return ResourceManager.GetString("P140101_NotSelectedMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未設定盤點儲位條件限制 的當地語系化字串。
        /// </summary>
        public static string P140101_NotSetLocLimit {
            get {
                return ResourceManager.GetString("P140101_NotSetLocLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已匯入明細資料將會被刪除，請確認是否要刪除 的當地語系化字串。
        /// </summary>
        public static string P140101_RepeatImportList {
            get {
                return ResourceManager.GetString("P140101_RepeatImportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 迄值不可小於起始值! 的當地語系化字串。
        /// </summary>
        public static string P140101_SelectedValueError {
            get {
                return ResourceManager.GetString("P140101_SelectedValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 詢問 的當地語系化字串。
        /// </summary>
        public static string P1401010000_Asking {
            get {
                return ResourceManager.GetString("P1401010000_Asking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢後會取代目前已存在的盤點商品清單,是否繼續查詢? 的當地語系化字串。
        /// </summary>
        public static string P1401010000_AskingForQueryWillReplaceInventoryItemList {
            get {
                return ResourceManager.GetString("P1401010000_AskingForQueryWillReplaceInventoryItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點倉別至少勾選一筆 的當地語系化字串。
        /// </summary>
        public static string P1401010000_AtleastOneInventoryWareHouseData {
            get {
                return ResourceManager.GetString("P1401010000_AtleastOneInventoryWareHouseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 勾選計費,費用必填 的當地語系化字串。
        /// </summary>
        public static string P1401010000_checkCount {
            get {
                return ResourceManager.GetString("P1401010000_checkCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此業主[ 的當地語系化字串。
        /// </summary>
        public static string P1401010000_Customer {
            get {
                return ResourceManager.GetString("P1401010000_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 循環盤次數必須小於等於週期 的當地語系化字串。
        /// </summary>
        public static string P1401010000_CycleTimesLessEqualThanCycle {
            get {
                return ResourceManager.GetString("P1401010000_CycleTimesLessEqualThanCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 入庫日 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ENTER_DATE {
            get {
                return ResourceManager.GetString("P1401010000_ENTER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 失敗盤點明細表 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ExcelName {
            get {
                return ResourceManager.GetString("P1401010000_ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料已存在 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ExistData {
            get {
                return ResourceManager.GetString("P1401010000_ExistData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出盤點單明細 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ExportInventoryDetail {
            get {
                return ResourceManager.GetString("P1401010000_ExportInventoryDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出盤點單明細失敗 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ExportInventoryDetailFail {
            get {
                return ResourceManager.GetString("P1401010000_ExportInventoryDetailFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出盤點失敗資料明細失敗 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ExportInventoryDetailFailDataFail {
            get {
                return ResourceManager.GetString("P1401010000_ExportInventoryDetailFailDataFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出盤點失敗資料明細成功 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ExportInventoryDetailFailDataSuccess {
            get {
                return ResourceManager.GetString("P1401010000_ExportInventoryDetailFailDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出盤點單明細成功 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ExportInventoryDetailSuccess {
            get {
                return ResourceManager.GetString("P1401010000_ExportInventoryDetailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 初盤數 的當地語系化字串。
        /// </summary>
        public static string P1401010000_FIRST_QTY {
            get {
                return ResourceManager.GetString("P1401010000_FIRST_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 初盤數必須大於等於0 的當地語系化字串。
        /// </summary>
        public static string P1401010000_FirstInventoryDetailQtyNeedMoreThanZero {
            get {
                return ResourceManager.GetString("P1401010000_FirstInventoryDetailQtyNeedMoreThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤盈可回沖 的當地語系化字串。
        /// </summary>
        public static string P1401010000_FLUSHBACKNAME {
            get {
                return ResourceManager.GetString("P1401010000_FLUSHBACKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入的Excel無資料 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ImportEmptyExcel {
            get {
                return ResourceManager.GetString("P1401010000_ImportEmptyExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入的Excel格式錯誤 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ImportErrorExcel {
            get {
                return ResourceManager.GetString("P1401010000_ImportErrorExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入的商品編號已存在盤點商品清單中 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ImportItemIsExistInInventoryItemList {
            get {
                return ResourceManager.GetString("P1401010000_ImportItemIsExistInInventoryItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在此條件下的盤點明細共有{0}筆，畫面僅顯示500筆 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ImportSearchDetailCountHint {
            get {
                return ResourceManager.GetString("P1401010000_ImportSearchDetailCountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入成功{0}筆(新增{1}筆+更新{2}筆)，失敗{3}筆，共{4}筆 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ImportSuccessDetail {
            get {
                return ResourceManager.GetString("P1401010000_ImportSuccessDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增失敗! 的當地語系化字串。
        /// </summary>
        public static string P1401010000_InsertFail {
            get {
                return ResourceManager.GetString("P1401010000_InsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增成功! 盤點單號:{0} 的當地語系化字串。
        /// </summary>
        public static string P1401010000_InsertSuccess {
            get {
                return ResourceManager.GetString("P1401010000_InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點單明細- 的當地語系化字串。
        /// </summary>
        public static string P1401010000_InventoryDetail {
            get {
                return ResourceManager.GetString("P1401010000_InventoryDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此儲位或商品非盤點範圍 的當地語系化字串。
        /// </summary>
        public static string P1401010000_InventoryLocItemNotValid {
            get {
                return ResourceManager.GetString("P1401010000_InventoryLocItemNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品號 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ITEM_CODE {
            get {
                return ResourceManager.GetString("P1401010000_ITEM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顏色 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ITEM_COLOR {
            get {
                return ResourceManager.GetString("P1401010000_ITEM_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品名 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ITEM_NAME {
            get {
                return ResourceManager.GetString("P1401010000_ITEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尺寸 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ITEM_SIZE {
            get {
                return ResourceManager.GetString("P1401010000_ITEM_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 規格 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ITEM_SPEC {
            get {
                return ResourceManager.GetString("P1401010000_ITEM_SPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此商品編號已存在盤點商品清單中 的當地語系化字串。
        /// </summary>
        public static string P1401010000_ItemIsExistInInventoryItemList {
            get {
                return ResourceManager.GetString("P1401010000_ItemIsExistInInventoryItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲位 的當地語系化字串。
        /// </summary>
        public static string P1401010000_LOC_CODE {
            get {
                return ResourceManager.GetString("P1401010000_LOC_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 週期必填 的當地語系化字串。
        /// </summary>
        public static string P1401010000_NeedCycle {
            get {
                return ResourceManager.GetString("P1401010000_NeedCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 循環盤次數必填 的當地語系化字串。
        /// </summary>
        public static string P1401010000_NeedCycleTimes {
            get {
                return ResourceManager.GetString("P1401010000_NeedCycleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點倉別必須設定通道起訖 的當地語系化字串。
        /// </summary>
        public static string P1401010000_NeedSetChannelBegin {
            get {
                return ResourceManager.GetString("P1401010000_NeedSetChannelBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點倉別必須設定樓層起訖 的當地語系化字串。
        /// </summary>
        public static string P1401010000_NeedSetFloorBegin {
            get {
                return ResourceManager.GetString("P1401010000_NeedSetFloorBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點倉別必須設定座起訖 的當地語系化字串。
        /// </summary>
        public static string P1401010000_NeedSetPlainBegin {
            get {
                return ResourceManager.GetString("P1401010000_NeedSetPlainBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ]無此商品編號[ 的當地語系化字串。
        /// </summary>
        public static string P1401010000_NoItemCode {
            get {
                return ResourceManager.GetString("P1401010000_NoItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 複盤數必須大於等於0 的當地語系化字串。
        /// </summary>
        public static string P1401010000_PluralInventoryDetailQtyNeedMoreThanZero {
            get {
                return ResourceManager.GetString("P1401010000_PluralInventoryDetailQtyNeedMoreThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫存數 的當地語系化字串。
        /// </summary>
        public static string P1401010000_QTY {
            get {
                return ResourceManager.GetString("P1401010000_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點日期 的當地語系化字串。
        /// </summary>
        public static string P1401010000_QueryInventoryEDate {
            get {
                return ResourceManager.GetString("P1401010000_QueryInventoryEDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 複盤數 的當地語系化字串。
        /// </summary>
        public static string P1401010000_SECOND_QTY {
            get {
                return ResourceManager.GetString("P1401010000_SECOND_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新失敗! 的當地語系化字串。
        /// </summary>
        public static string P1401010000_UpdateFail {
            get {
                return ResourceManager.GetString("P1401010000_UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 效期 的當地語系化字串。
        /// </summary>
        public static string P1401010000_VALID_DATE {
            get {
                return ResourceManager.GetString("P1401010000_VALID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 倉別 的當地語系化字串。
        /// </summary>
        public static string P1401010000_WAREHOUSE_NAME {
            get {
                return ResourceManager.GetString("P1401010000_WAREHOUSE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入失敗! 的當地語系化字串。
        /// </summary>
        public static string P1401010000xamlcs_ImportFail {
            get {
                return ResourceManager.GetString("P1401010000xamlcs_ImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  盤點單 的當地語系化字串。
        /// </summary>
        public static string P1401010000xamlcs_Inventory {
            get {
                return ResourceManager.GetString("P1401010000xamlcs_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  盤點清冊 的當地語系化字串。
        /// </summary>
        public static string P1401010000xamlcs_IventoryList {
            get {
                return ResourceManager.GetString("P1401010000xamlcs_IventoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  查詢無資料，無法預覽或列印！ 的當地語系化字串。
        /// </summary>
        public static string P1401010000xamlcs_QueryDataEmpty {
            get {
                return ResourceManager.GetString("P1401010000xamlcs_QueryDataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該商品已經加入! 的當地語系化字串。
        /// </summary>
        public static string P1401020000_AlreadyExistItem {
            get {
                return ResourceManager.GetString("P1401020000_AlreadyExistItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尚未匯入盤點資料，是否確認產生盤點差異結果 的當地語系化字串。
        /// </summary>
        public static string P1401020000_CheckingGenerInventoryDiff {
            get {
                return ResourceManager.GetString("P1401020000_CheckingGenerInventoryDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先查詢盤點單資料 的當地語系化字串。
        /// </summary>
        public static string P1401020000_CheckingIsCanSaveInventoryData {
            get {
                return ResourceManager.GetString("P1401020000_CheckingIsCanSaveInventoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 複盤差異數資料已存在，確認清空資料重新產生複盤資料 的當地語系化字串。
        /// </summary>
        public static string P1401020000_CheckingRegenerPluralDiffData {
            get {
                return ResourceManager.GetString("P1401020000_CheckingRegenerPluralDiffData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請勾選盤點單明細資料 的當地語系化字串。
        /// </summary>
        public static string P1401020000_CheckingSelectedIsExistDatas {
            get {
                return ResourceManager.GetString("P1401020000_CheckingSelectedIsExistDatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品編號不得為空! 的當地語系化字串。
        /// </summary>
        public static string P1401020000_ItemCodeIsEmpty {
            get {
                return ResourceManager.GetString("P1401020000_ItemCodeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尚未輸入任何商品! 的當地語系化字串。
        /// </summary>
        public static string P1401020000_ItemIsEmpty {
            get {
                return ResourceManager.GetString("P1401020000_ItemIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 批號不得為空! 的當地語系化字串。
        /// </summary>
        public static string P1401020000_MakeNoEmpty {
            get {
                return ResourceManager.GetString("P1401020000_MakeNoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 批號長度不可超過40碼 的當地語系化字串。
        /// </summary>
        public static string P1401020000_MakeNoLengthOver {
            get {
                return ResourceManager.GetString("P1401020000_MakeNoLengthOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本次盤點無差異或者不接受任何差異? 的當地語系化字串。
        /// </summary>
        public static string P1401020000_NotDiffMsg {
            get {
                return ResourceManager.GetString("P1401020000_NotDiffMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本次盤點無差異，不需建立複盤單 的當地語系化字串。
        /// </summary>
        public static string P1401020000_NotNeedRegenerate {
            get {
                return ResourceManager.GetString("P1401020000_NotNeedRegenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 差異數量區間不得為空! 的當地語系化字串。
        /// </summary>
        public static string P1401020000_RangeDiffIsEmpty {
            get {
                return ResourceManager.GetString("P1401020000_RangeDiffIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請將篩選條件一選倉別全部、篩選條件二選全部差異商品進行查詢盤點資料後，並確認差異在進行產生複盤資料 的當地語系化字串。
        /// </summary>
        public static string P1401020000_RegenerateInventoryConditionError {
            get {
                return ResourceManager.GetString("P1401020000_RegenerateInventoryConditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點差異數或盤點庫差數不等於0才可以複盤 的當地語系化字串。
        /// </summary>
        public static string P1401020000_RegenerateInventoryConditionError_2 {
            get {
                return ResourceManager.GetString("P1401020000_RegenerateInventoryConditionError_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請將篩選條件一選倉別全部、篩選條件二選全部差異商品進行查詢盤點資料後，並確認差異在進行盤點確認 的當地語系化字串。
        /// </summary>
        public static string P1401020000_SaveInventoryConditionError {
            get {
                return ResourceManager.GetString("P1401020000_SaveInventoryConditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先選取盤點單資料! 的當地語系化字串。
        /// </summary>
        public static string P1401020000_SelectInventoryDataFirst {
            get {
                return ResourceManager.GetString("P1401020000_SelectInventoryDataFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點差異數(B-A)
        ///(1)人工倉的系統庫存來自WMS系統、自動倉的系統庫存來自自動倉的系統。
        ///(2)若自動倉的盤點差異數&gt;0時，按下&lt;盤點確認&gt;會下發盤點調整任務。
        ///
        ///結案按鈕: 盤點單無任何盤差數或庫差數時，人員可手動執行將此盤點單結案 的當地語系化字串。
        /// </summary>
        public static string P1401020000_Wording_1 {
            get {
                return ResourceManager.GetString("P1401020000_Wording_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WMS系統庫存差異數(B-X-Y)
        ///(1)當盤點儲位屬於人工倉時，A=X。
        ///(2)若盤點差異數=0，而WMS系統庫存差異數&gt;0 時，按下&lt;盤點確認&gt;，只調整WMS的庫存。 的當地語系化字串。
        /// </summary>
        public static string P1401020000_Wording_2 {
            get {
                return ResourceManager.GetString("P1401020000_Wording_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;盤點比對說明&gt; 請在庫存靜止狀態下進行盤點。 的當地語系化字串。
        /// </summary>
        public static string P1401020000_WordingHeader {
            get {
                return ResourceManager.GetString("P1401020000_WordingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  請選取盤點單！ 的當地語系化字串。
        /// </summary>
        public static string P1401020000xamlcs_ChooseInventory {
            get {
                return ResourceManager.GetString("P1401020000xamlcs_ChooseInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  盤點差異表 的當地語系化字串。
        /// </summary>
        public static string P1401020000xamlcs_DifferentInventory {
            get {
                return ResourceManager.GetString("P1401020000xamlcs_DifferentInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品編號已重覆 的當地語系化字串。
        /// </summary>
        public static string P1401040000_ItemCodeIsExist {
            get {
                return ResourceManager.GetString("P1401040000_ItemCodeIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請勾選要刪除的商品 的當地語系化字串。
        /// </summary>
        public static string P1401040000_SelectFilterProductList {
            get {
                return ResourceManager.GetString("P1401040000_SelectFilterProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  盤盈損資料表 的當地語系化字串。
        /// </summary>
        public static string P1401040000xamlcs_BalanceSheet {
            get {
                return ResourceManager.GetString("P1401040000xamlcs_BalanceSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 板號 的當地語系化字串。
        /// </summary>
        public static string PALLET_CTRL_NO {
            get {
                return ResourceManager.GetString("PALLET_CTRL_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 座起 的當地語系化字串。
        /// </summary>
        public static string PLAIN_BEGIN {
            get {
                return ResourceManager.GetString("PLAIN_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 座迄 的當地語系化字串。
        /// </summary>
        public static string PLAIN_END {
            get {
                return ResourceManager.GetString("PLAIN_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 過帳日期 的當地語系化字串。
        /// </summary>
        public static string PostingDateBegin {
            get {
                return ResourceManager.GetString("PostingDateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤盈數 的當地語系化字串。
        /// </summary>
        public static string PROFIT_QTY {
            get {
                return ResourceManager.GetString("PROFIT_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫存數 的當地語系化字串。
        /// </summary>
        public static string QTY {
            get {
                return ResourceManager.GetString("QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫存數 的當地語系化字串。
        /// </summary>
        public static string Qty_Count {
            get {
                return ResourceManager.GetString("Qty_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統庫存數量(A) 的當地語系化字串。
        /// </summary>
        public static string QtyCount {
            get {
                return ResourceManager.GetString("QtyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲位範圍 的當地語系化字串。
        /// </summary>
        public static string QueryDetailBegLocCode {
            get {
                return ResourceManager.GetString("QueryDetailBegLocCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點單明細 的當地語系化字串。
        /// </summary>
        public static string QueryDetailWareHouseList {
            get {
                return ResourceManager.GetString("QueryDetailWareHouseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 倉別 的當地語系化字串。
        /// </summary>
        public static string QueryDetialWareHouseId {
            get {
                return ResourceManager.GetString("QueryDetialWareHouseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點單號 的當地語系化字串。
        /// </summary>
        public static string QueryInventoryNo {
            get {
                return ResourceManager.GetString("QueryInventoryNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點日期 的當地語系化字串。
        /// </summary>
        public static string QueryInventorySDate {
            get {
                return ResourceManager.GetString("QueryInventorySDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ～ 的當地語系化字串。
        /// </summary>
        public static string RangeEnd {
            get {
                return ResourceManager.GetString("RangeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 倒回庫存關帳點 的當地語系化字串。
        /// </summary>
        public static string RbBackClosePoint {
            get {
                return ResourceManager.GetString("RbBackClosePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 拷貝庫存關帳點 的當地語系化字串。
        /// </summary>
        public static string RbClosePoint {
            get {
                return ResourceManager.GetString("RbClosePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產生複盤資料 的當地語系化字串。
        /// </summary>
        public static string RegenerateInventoryData {
            get {
                return ResourceManager.GetString("RegenerateInventoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點確認 的當地語系化字串。
        /// </summary>
        public static string SaveInventoryData {
            get {
                return ResourceManager.GetString("SaveInventoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢明細 的當地語系化字串。
        /// </summary>
        public static string SearchDetail {
            get {
                return ResourceManager.GetString("SearchDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢盤點單資料 的當地語系化字串。
        /// </summary>
        public static string SearchDetailData {
            get {
                return ResourceManager.GetString("SearchDetailData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 複盤時間 的當地語系化字串。
        /// </summary>
        public static string SEC_INVENTORY_DATE {
            get {
                return ResourceManager.GetString("SEC_INVENTORY_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 複盤人員 的當地語系化字串。
        /// </summary>
        public static string SEC_INVENTORY_NAME {
            get {
                return ResourceManager.GetString("SEC_INVENTORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 篩選條件二 的當地語系化字串。
        /// </summary>
        public static string Second_Condition {
            get {
                return ResourceManager.GetString("Second_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 複盤數 的當地語系化字串。
        /// </summary>
        public static string SECOND_QTY {
            get {
                return ResourceManager.GetString("SECOND_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 倒回關帳點： 的當地語系化字串。
        /// </summary>
        public static string SelectBackClosePoint {
            get {
                return ResourceManager.GetString("SelectBackClosePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 大類 的當地語系化字串。
        /// </summary>
        public static string SelectedItemLType {
            get {
                return ResourceManager.GetString("SelectedItemLType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 中類 的當地語系化字串。
        /// </summary>
        public static string SelectedItemMType {
            get {
                return ResourceManager.GetString("SelectedItemMType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 小類 的當地語系化字串。
        /// </summary>
        public static string SelectedItemSType {
            get {
                return ResourceManager.GetString("SelectedItemSType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報表種類 的當地語系化字串。
        /// </summary>
        public static string SelectedReportType {
            get {
                return ResourceManager.GetString("SelectedReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單據狀態 的當地語系化字串。
        /// </summary>
        public static string SelectedStatus {
            get {
                return ResourceManager.GetString("SelectedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 指定倉別 的當地語系化字串。
        /// </summary>
        public static string SelectedWareHouseId {
            get {
                return ResourceManager.GetString("SelectedWareHouseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 指定商品： 的當地語系化字串。
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點狀態 的當地語系化字串。
        /// </summary>
        public static string SelectStatus {
            get {
                return ResourceManager.GetString("SelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 全部設為盤盈可回沖 的當地語系化字串。
        /// </summary>
        public static string SetAllFlushback {
            get {
                return ResourceManager.GetString("SetAllFlushback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點顯示數量 的當地語系化字串。
        /// </summary>
        public static string SHOW_CNT {
            get {
                return ResourceManager.GetString("SHOW_CNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 依差異數量排序 的當地語系化字串。
        /// </summary>
        public static string SortByCount {
            get {
                return ResourceManager.GetString("SortByCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序條件： 的當地語系化字串。
        /// </summary>
        public static string SortCondition {
            get {
                return ResourceManager.GetString("SortCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作站 的當地語系化字串。
        /// </summary>
        public static string STATION_NO {
            get {
                return ResourceManager.GetString("STATION_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WMS系統庫存差異數(B-X-Y) 的當地語系化字串。
        /// </summary>
        public static string STOCK_DIFF_QTY {
            get {
                return ResourceManager.GetString("STOCK_DIFF_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 次 的當地語系化字串。
        /// </summary>
        public static string TIMES {
            get {
                return ResourceManager.GetString("TIMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WMS未搬動數量 的當地語系化字串。
        /// </summary>
        public static string UnmovedQty {
            get {
                return ResourceManager.GetString("UnmovedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WMS已扣帳但未下架數(Y) 的當地語系化字串。
        /// </summary>
        public static string UnmoveStockQty {
            get {
                return ResourceManager.GetString("UnmoveStockQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 異動時間 的當地語系化字串。
        /// </summary>
        public static string UPD_DATE {
            get {
                return ResourceManager.GetString("UPD_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 效期 的當地語系化字串。
        /// </summary>
        public static string VALID_DATE {
            get {
                return ResourceManager.GetString("VALID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 效期 的當地語系化字串。
        /// </summary>
        public static string ValidDate {
            get {
                return ResourceManager.GetString("ValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 倉別名稱 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_NAME {
            get {
                return ResourceManager.GetString("WAREHOUSE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 指定倉別： 的當地語系化字串。
        /// </summary>
        public static string WarehouseId {
            get {
                return ResourceManager.GetString("WarehouseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 倉別 的當地語系化字串。
        /// </summary>
        public static string WarehouseName {
            get {
                return ResourceManager.GetString("WarehouseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 倉別類型 的當地語系化字串。
        /// </summary>
        public static string WareHouseType {
            get {
                return ResourceManager.GetString("WareHouseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WMS單號 的當地語系化字串。
        /// </summary>
        public static string WMS_NO {
            get {
                return ResourceManager.GetString("WMS_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WMS系統庫存數量(X) 的當地語系化字串。
        /// </summary>
        public static string WmsQtyCount {
            get {
                return ResourceManager.GetString("WmsQtyCount", resourceCulture);
            }
        }
    }
}
