//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms3pl.WpfClient.ExDataServices.P20WcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecuteResult", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class ExecuteResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessed {
            get {
                return this.IsSuccessedField;
            }
            set {
                if ((this.IsSuccessedField.Equals(value) != true)) {
                    this.IsSuccessedField = value;
                    this.RaisePropertyChanged("IsSuccessed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="F050301Data", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class F050301Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ADDRESSk__BackingFieldField;
        
        private string CONSIGNEEk__BackingFieldField;
        
        private string CUST_CODEk__BackingFieldField;
        
        private string CUST_ORD_NOk__BackingFieldField;
        
        private string DC_CODEk__BackingFieldField;
        
        private System.Nullable<System.DateTime> DELV_DATEk__BackingFieldField;
        
        private string GUP_CODEk__BackingFieldField;
        
        private bool IsSelectedk__BackingFieldField;
        
        private string ORD_NOk__BackingFieldField;
        
        private string ORD_TYPEk__BackingFieldField;
        
        private string PICK_TIMEk__BackingFieldField;
        
        private int ROWNUMk__BackingFieldField;
        
        private string ZIP_CODEk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ADDRESS>k__BackingField", IsRequired=true)]
        public string ADDRESSk__BackingField {
            get {
                return this.ADDRESSk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ADDRESSk__BackingFieldField, value) != true)) {
                    this.ADDRESSk__BackingFieldField = value;
                    this.RaisePropertyChanged("ADDRESSk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CONSIGNEE>k__BackingField", IsRequired=true)]
        public string CONSIGNEEk__BackingField {
            get {
                return this.CONSIGNEEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CONSIGNEEk__BackingFieldField, value) != true)) {
                    this.CONSIGNEEk__BackingFieldField = value;
                    this.RaisePropertyChanged("CONSIGNEEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CUST_CODE>k__BackingField", IsRequired=true)]
        public string CUST_CODEk__BackingField {
            get {
                return this.CUST_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_CODEk__BackingFieldField, value) != true)) {
                    this.CUST_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("CUST_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CUST_ORD_NO>k__BackingField", IsRequired=true)]
        public string CUST_ORD_NOk__BackingField {
            get {
                return this.CUST_ORD_NOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_ORD_NOk__BackingFieldField, value) != true)) {
                    this.CUST_ORD_NOk__BackingFieldField = value;
                    this.RaisePropertyChanged("CUST_ORD_NOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DC_CODE>k__BackingField", IsRequired=true)]
        public string DC_CODEk__BackingField {
            get {
                return this.DC_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DC_CODEk__BackingFieldField, value) != true)) {
                    this.DC_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("DC_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DELV_DATE>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> DELV_DATEk__BackingField {
            get {
                return this.DELV_DATEk__BackingFieldField;
            }
            set {
                if ((this.DELV_DATEk__BackingFieldField.Equals(value) != true)) {
                    this.DELV_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("DELV_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<GUP_CODE>k__BackingField", IsRequired=true)]
        public string GUP_CODEk__BackingField {
            get {
                return this.GUP_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.GUP_CODEk__BackingFieldField, value) != true)) {
                    this.GUP_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("GUP_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsSelected>k__BackingField", IsRequired=true)]
        public bool IsSelectedk__BackingField {
            get {
                return this.IsSelectedk__BackingFieldField;
            }
            set {
                if ((this.IsSelectedk__BackingFieldField.Equals(value) != true)) {
                    this.IsSelectedk__BackingFieldField = value;
                    this.RaisePropertyChanged("IsSelectedk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ORD_NO>k__BackingField", IsRequired=true)]
        public string ORD_NOk__BackingField {
            get {
                return this.ORD_NOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ORD_NOk__BackingFieldField, value) != true)) {
                    this.ORD_NOk__BackingFieldField = value;
                    this.RaisePropertyChanged("ORD_NOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ORD_TYPE>k__BackingField", IsRequired=true)]
        public string ORD_TYPEk__BackingField {
            get {
                return this.ORD_TYPEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ORD_TYPEk__BackingFieldField, value) != true)) {
                    this.ORD_TYPEk__BackingFieldField = value;
                    this.RaisePropertyChanged("ORD_TYPEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PICK_TIME>k__BackingField", IsRequired=true)]
        public string PICK_TIMEk__BackingField {
            get {
                return this.PICK_TIMEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PICK_TIMEk__BackingFieldField, value) != true)) {
                    this.PICK_TIMEk__BackingFieldField = value;
                    this.RaisePropertyChanged("PICK_TIMEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ROWNUM>k__BackingField", IsRequired=true)]
        public int ROWNUMk__BackingField {
            get {
                return this.ROWNUMk__BackingFieldField;
            }
            set {
                if ((this.ROWNUMk__BackingFieldField.Equals(value) != true)) {
                    this.ROWNUMk__BackingFieldField = value;
                    this.RaisePropertyChanged("ROWNUMk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ZIP_CODE>k__BackingField", IsRequired=true)]
        public string ZIP_CODEk__BackingField {
            get {
                return this.ZIP_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ZIP_CODEk__BackingFieldField, value) != true)) {
                    this.ZIP_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("ZIP_CODEk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="F1913Data", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class F1913Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ADJ_QTY_INField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ADJ_QTY_OUTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BOX_CTRL_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BUNDLE_SERIALLOCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BUNDLE_SERIALNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAUSEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAUSENAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAUSE_MEMOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUST_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUST_ITEM_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DC_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DC_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DEVICE_STOCK_QTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DIFF_QTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EAN_CODE1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EAN_CODE2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EAN_CODE3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ENTER_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUP_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> INVENTORY_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INVENTORY_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int INVENTORY_QTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ISADDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IS_FLUSHBACKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITEM_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITEM_COLORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITEM_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITEM_SIZEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITEM_SPECField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOC_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MAKE_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PALLET_CTRL_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PERSON_CONFIRM_STATUS_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROC_WMS_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long QTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ROWNUMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SERIALNO_SCANOKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SERIAL_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int STOCK_DIFF_QTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UNMOVE_STOCK_QTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VALID_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VNR_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VNR_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WAREHOUSE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WAREHOUSE_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WMS_STATUS_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WORK_TYPEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ADJ_QTY_IN {
            get {
                return this.ADJ_QTY_INField;
            }
            set {
                if ((this.ADJ_QTY_INField.Equals(value) != true)) {
                    this.ADJ_QTY_INField = value;
                    this.RaisePropertyChanged("ADJ_QTY_IN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ADJ_QTY_OUT {
            get {
                return this.ADJ_QTY_OUTField;
            }
            set {
                if ((this.ADJ_QTY_OUTField.Equals(value) != true)) {
                    this.ADJ_QTY_OUTField = value;
                    this.RaisePropertyChanged("ADJ_QTY_OUT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BOX_CTRL_NO {
            get {
                return this.BOX_CTRL_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.BOX_CTRL_NOField, value) != true)) {
                    this.BOX_CTRL_NOField = value;
                    this.RaisePropertyChanged("BOX_CTRL_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BUNDLE_SERIALLOC {
            get {
                return this.BUNDLE_SERIALLOCField;
            }
            set {
                if ((object.ReferenceEquals(this.BUNDLE_SERIALLOCField, value) != true)) {
                    this.BUNDLE_SERIALLOCField = value;
                    this.RaisePropertyChanged("BUNDLE_SERIALLOC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BUNDLE_SERIALNO {
            get {
                return this.BUNDLE_SERIALNOField;
            }
            set {
                if ((object.ReferenceEquals(this.BUNDLE_SERIALNOField, value) != true)) {
                    this.BUNDLE_SERIALNOField = value;
                    this.RaisePropertyChanged("BUNDLE_SERIALNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CAUSE {
            get {
                return this.CAUSEField;
            }
            set {
                if ((object.ReferenceEquals(this.CAUSEField, value) != true)) {
                    this.CAUSEField = value;
                    this.RaisePropertyChanged("CAUSE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CAUSENAME {
            get {
                return this.CAUSENAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.CAUSENAMEField, value) != true)) {
                    this.CAUSENAMEField = value;
                    this.RaisePropertyChanged("CAUSENAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CAUSE_MEMO {
            get {
                return this.CAUSE_MEMOField;
            }
            set {
                if ((object.ReferenceEquals(this.CAUSE_MEMOField, value) != true)) {
                    this.CAUSE_MEMOField = value;
                    this.RaisePropertyChanged("CAUSE_MEMO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUST_CODE {
            get {
                return this.CUST_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_CODEField, value) != true)) {
                    this.CUST_CODEField = value;
                    this.RaisePropertyChanged("CUST_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUST_ITEM_CODE {
            get {
                return this.CUST_ITEM_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_ITEM_CODEField, value) != true)) {
                    this.CUST_ITEM_CODEField = value;
                    this.RaisePropertyChanged("CUST_ITEM_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DC_CODE {
            get {
                return this.DC_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.DC_CODEField, value) != true)) {
                    this.DC_CODEField = value;
                    this.RaisePropertyChanged("DC_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DC_NAME {
            get {
                return this.DC_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.DC_NAMEField, value) != true)) {
                    this.DC_NAMEField = value;
                    this.RaisePropertyChanged("DC_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DEVICE_STOCK_QTY {
            get {
                return this.DEVICE_STOCK_QTYField;
            }
            set {
                if ((this.DEVICE_STOCK_QTYField.Equals(value) != true)) {
                    this.DEVICE_STOCK_QTYField = value;
                    this.RaisePropertyChanged("DEVICE_STOCK_QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DIFF_QTY {
            get {
                return this.DIFF_QTYField;
            }
            set {
                if ((this.DIFF_QTYField.Equals(value) != true)) {
                    this.DIFF_QTYField = value;
                    this.RaisePropertyChanged("DIFF_QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EAN_CODE1 {
            get {
                return this.EAN_CODE1Field;
            }
            set {
                if ((object.ReferenceEquals(this.EAN_CODE1Field, value) != true)) {
                    this.EAN_CODE1Field = value;
                    this.RaisePropertyChanged("EAN_CODE1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EAN_CODE2 {
            get {
                return this.EAN_CODE2Field;
            }
            set {
                if ((object.ReferenceEquals(this.EAN_CODE2Field, value) != true)) {
                    this.EAN_CODE2Field = value;
                    this.RaisePropertyChanged("EAN_CODE2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EAN_CODE3 {
            get {
                return this.EAN_CODE3Field;
            }
            set {
                if ((object.ReferenceEquals(this.EAN_CODE3Field, value) != true)) {
                    this.EAN_CODE3Field = value;
                    this.RaisePropertyChanged("EAN_CODE3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ENTER_DATE {
            get {
                return this.ENTER_DATEField;
            }
            set {
                if ((this.ENTER_DATEField.Equals(value) != true)) {
                    this.ENTER_DATEField = value;
                    this.RaisePropertyChanged("ENTER_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GUP_CODE {
            get {
                return this.GUP_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.GUP_CODEField, value) != true)) {
                    this.GUP_CODEField = value;
                    this.RaisePropertyChanged("GUP_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> INVENTORY_DATE {
            get {
                return this.INVENTORY_DATEField;
            }
            set {
                if ((this.INVENTORY_DATEField.Equals(value) != true)) {
                    this.INVENTORY_DATEField = value;
                    this.RaisePropertyChanged("INVENTORY_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string INVENTORY_NAME {
            get {
                return this.INVENTORY_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.INVENTORY_NAMEField, value) != true)) {
                    this.INVENTORY_NAMEField = value;
                    this.RaisePropertyChanged("INVENTORY_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int INVENTORY_QTY {
            get {
                return this.INVENTORY_QTYField;
            }
            set {
                if ((this.INVENTORY_QTYField.Equals(value) != true)) {
                    this.INVENTORY_QTYField = value;
                    this.RaisePropertyChanged("INVENTORY_QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ISADD {
            get {
                return this.ISADDField;
            }
            set {
                if ((this.ISADDField.Equals(value) != true)) {
                    this.ISADDField = value;
                    this.RaisePropertyChanged("ISADD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IS_FLUSHBACK {
            get {
                return this.IS_FLUSHBACKField;
            }
            set {
                if ((object.ReferenceEquals(this.IS_FLUSHBACKField, value) != true)) {
                    this.IS_FLUSHBACKField = value;
                    this.RaisePropertyChanged("IS_FLUSHBACK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITEM_CODE {
            get {
                return this.ITEM_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_CODEField, value) != true)) {
                    this.ITEM_CODEField = value;
                    this.RaisePropertyChanged("ITEM_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITEM_COLOR {
            get {
                return this.ITEM_COLORField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_COLORField, value) != true)) {
                    this.ITEM_COLORField = value;
                    this.RaisePropertyChanged("ITEM_COLOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITEM_NAME {
            get {
                return this.ITEM_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_NAMEField, value) != true)) {
                    this.ITEM_NAMEField = value;
                    this.RaisePropertyChanged("ITEM_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITEM_SIZE {
            get {
                return this.ITEM_SIZEField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_SIZEField, value) != true)) {
                    this.ITEM_SIZEField = value;
                    this.RaisePropertyChanged("ITEM_SIZE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITEM_SPEC {
            get {
                return this.ITEM_SPECField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_SPECField, value) != true)) {
                    this.ITEM_SPECField = value;
                    this.RaisePropertyChanged("ITEM_SPEC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOC_CODE {
            get {
                return this.LOC_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.LOC_CODEField, value) != true)) {
                    this.LOC_CODEField = value;
                    this.RaisePropertyChanged("LOC_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MAKE_NO {
            get {
                return this.MAKE_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.MAKE_NOField, value) != true)) {
                    this.MAKE_NOField = value;
                    this.RaisePropertyChanged("MAKE_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PALLET_CTRL_NO {
            get {
                return this.PALLET_CTRL_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PALLET_CTRL_NOField, value) != true)) {
                    this.PALLET_CTRL_NOField = value;
                    this.RaisePropertyChanged("PALLET_CTRL_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PERSON_CONFIRM_STATUS_NAME {
            get {
                return this.PERSON_CONFIRM_STATUS_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.PERSON_CONFIRM_STATUS_NAMEField, value) != true)) {
                    this.PERSON_CONFIRM_STATUS_NAMEField = value;
                    this.RaisePropertyChanged("PERSON_CONFIRM_STATUS_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROC_WMS_NO {
            get {
                return this.PROC_WMS_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PROC_WMS_NOField, value) != true)) {
                    this.PROC_WMS_NOField = value;
                    this.RaisePropertyChanged("PROC_WMS_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long QTY {
            get {
                return this.QTYField;
            }
            set {
                if ((this.QTYField.Equals(value) != true)) {
                    this.QTYField = value;
                    this.RaisePropertyChanged("QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ROWNUM {
            get {
                return this.ROWNUMField;
            }
            set {
                if ((this.ROWNUMField.Equals(value) != true)) {
                    this.ROWNUMField = value;
                    this.RaisePropertyChanged("ROWNUM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SERIALNO_SCANOK {
            get {
                return this.SERIALNO_SCANOKField;
            }
            set {
                if ((object.ReferenceEquals(this.SERIALNO_SCANOKField, value) != true)) {
                    this.SERIALNO_SCANOKField = value;
                    this.RaisePropertyChanged("SERIALNO_SCANOK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SERIAL_NO {
            get {
                return this.SERIAL_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.SERIAL_NOField, value) != true)) {
                    this.SERIAL_NOField = value;
                    this.RaisePropertyChanged("SERIAL_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STATUS {
            get {
                return this.STATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.STATUSField, value) != true)) {
                    this.STATUSField = value;
                    this.RaisePropertyChanged("STATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int STOCK_DIFF_QTY {
            get {
                return this.STOCK_DIFF_QTYField;
            }
            set {
                if ((this.STOCK_DIFF_QTYField.Equals(value) != true)) {
                    this.STOCK_DIFF_QTYField = value;
                    this.RaisePropertyChanged("STOCK_DIFF_QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UNMOVE_STOCK_QTY {
            get {
                return this.UNMOVE_STOCK_QTYField;
            }
            set {
                if ((this.UNMOVE_STOCK_QTYField.Equals(value) != true)) {
                    this.UNMOVE_STOCK_QTYField = value;
                    this.RaisePropertyChanged("UNMOVE_STOCK_QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VALID_DATE {
            get {
                return this.VALID_DATEField;
            }
            set {
                if ((this.VALID_DATEField.Equals(value) != true)) {
                    this.VALID_DATEField = value;
                    this.RaisePropertyChanged("VALID_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VNR_CODE {
            get {
                return this.VNR_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.VNR_CODEField, value) != true)) {
                    this.VNR_CODEField = value;
                    this.RaisePropertyChanged("VNR_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VNR_NAME {
            get {
                return this.VNR_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.VNR_NAMEField, value) != true)) {
                    this.VNR_NAMEField = value;
                    this.RaisePropertyChanged("VNR_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WAREHOUSE_ID {
            get {
                return this.WAREHOUSE_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.WAREHOUSE_IDField, value) != true)) {
                    this.WAREHOUSE_IDField = value;
                    this.RaisePropertyChanged("WAREHOUSE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WAREHOUSE_NAME {
            get {
                return this.WAREHOUSE_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.WAREHOUSE_NAMEField, value) != true)) {
                    this.WAREHOUSE_NAMEField = value;
                    this.RaisePropertyChanged("WAREHOUSE_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WMS_STATUS_NAME {
            get {
                return this.WMS_STATUS_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.WMS_STATUS_NAMEField, value) != true)) {
                    this.WMS_STATUS_NAMEField = value;
                    this.RaisePropertyChanged("WMS_STATUS_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WORK_TYPE {
            get {
                return this.WORK_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.WORK_TYPEField, value) != true)) {
                    this.WORK_TYPEField = value;
                    this.RaisePropertyChanged("WORK_TYPE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerialNoResult", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class SerialNoResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatchNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoxSerailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CheckedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CombinNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentlyStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PukField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SEQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string boxCtrlNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string palletCtrlNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatchNo {
            get {
                return this.BatchNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchNoField, value) != true)) {
                    this.BatchNoField = value;
                    this.RaisePropertyChanged("BatchNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BoxSerail {
            get {
                return this.BoxSerailField;
            }
            set {
                if ((object.ReferenceEquals(this.BoxSerailField, value) != true)) {
                    this.BoxSerailField = value;
                    this.RaisePropertyChanged("BoxSerail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseNo {
            get {
                return this.CaseNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseNoField, value) != true)) {
                    this.CaseNoField = value;
                    this.RaisePropertyChanged("CaseNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellNum {
            get {
                return this.CellNumField;
            }
            set {
                if ((object.ReferenceEquals(this.CellNumField, value) != true)) {
                    this.CellNumField = value;
                    this.RaisePropertyChanged("CellNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Checked {
            get {
                return this.CheckedField;
            }
            set {
                if ((this.CheckedField.Equals(value) != true)) {
                    this.CheckedField = value;
                    this.RaisePropertyChanged("Checked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CombinNo {
            get {
                return this.CombinNoField;
            }
            set {
                if ((this.CombinNoField.Equals(value) != true)) {
                    this.CombinNoField = value;
                    this.RaisePropertyChanged("CombinNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentlyStatus {
            get {
                return this.CurrentlyStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentlyStatusField, value) != true)) {
                    this.CurrentlyStatusField = value;
                    this.RaisePropertyChanged("CurrentlyStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemColor {
            get {
                return this.ItemColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemColorField, value) != true)) {
                    this.ItemColorField = value;
                    this.RaisePropertyChanged("ItemColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemSize {
            get {
                return this.ItemSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemSizeField, value) != true)) {
                    this.ItemSizeField = value;
                    this.RaisePropertyChanged("ItemSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeNo {
            get {
                return this.MakeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeNoField, value) != true)) {
                    this.MakeNoField = value;
                    this.RaisePropertyChanged("MakeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Puk {
            get {
                return this.PukField;
            }
            set {
                if ((object.ReferenceEquals(this.PukField, value) != true)) {
                    this.PukField = value;
                    this.RaisePropertyChanged("Puk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SEQ {
            get {
                return this.SEQField;
            }
            set {
                if ((this.SEQField.Equals(value) != true)) {
                    this.SEQField = value;
                    this.RaisePropertyChanged("SEQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNo {
            get {
                return this.SerialNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNoField, value) != true)) {
                    this.SerialNoField = value;
                    this.RaisePropertyChanged("SerialNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string boxCtrlNo {
            get {
                return this.boxCtrlNoField;
            }
            set {
                if ((object.ReferenceEquals(this.boxCtrlNoField, value) != true)) {
                    this.boxCtrlNoField = value;
                    this.RaisePropertyChanged("boxCtrlNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string palletCtrlNo {
            get {
                return this.palletCtrlNoField;
            }
            set {
                if ((object.ReferenceEquals(this.palletCtrlNoField, value) != true)) {
                    this.palletCtrlNoField = value;
                    this.RaisePropertyChanged("palletCtrlNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="F1913DataImport", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class F1913DataImport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ADJ_QTY_INk__BackingFieldField;
        
        private string ADJ_QTY_OUTk__BackingFieldField;
        
        private string CAUSENAMEk__BackingFieldField;
        
        private string CAUSE_MEMOk__BackingFieldField;
        
        private string CAUSEk__BackingFieldField;
        
        private string DC_CODEk__BackingFieldField;
        
        private string ENTER_DATE_FORMATk__BackingFieldField;
        
        private string ENTER_DATEk__BackingFieldField;
        
        private string FailMessagek__BackingFieldField;
        
        private string ITEM_CODEk__BackingFieldField;
        
        private string LOC_CODEk__BackingFieldField;
        
        private string MAKE_NOk__BackingFieldField;
        
        private decimal ROWNUMk__BackingFieldField;
        
        private string SERIAL_NOk__BackingFieldField;
        
        private string VALID_DATE_FORMATk__BackingFieldField;
        
        private string VALID_DATEk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ADJ_QTY_IN>k__BackingField", IsRequired=true)]
        public string ADJ_QTY_INk__BackingField {
            get {
                return this.ADJ_QTY_INk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ADJ_QTY_INk__BackingFieldField, value) != true)) {
                    this.ADJ_QTY_INk__BackingFieldField = value;
                    this.RaisePropertyChanged("ADJ_QTY_INk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ADJ_QTY_OUT>k__BackingField", IsRequired=true)]
        public string ADJ_QTY_OUTk__BackingField {
            get {
                return this.ADJ_QTY_OUTk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ADJ_QTY_OUTk__BackingFieldField, value) != true)) {
                    this.ADJ_QTY_OUTk__BackingFieldField = value;
                    this.RaisePropertyChanged("ADJ_QTY_OUTk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CAUSENAME>k__BackingField", IsRequired=true)]
        public string CAUSENAMEk__BackingField {
            get {
                return this.CAUSENAMEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CAUSENAMEk__BackingFieldField, value) != true)) {
                    this.CAUSENAMEk__BackingFieldField = value;
                    this.RaisePropertyChanged("CAUSENAMEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CAUSE_MEMO>k__BackingField", IsRequired=true)]
        public string CAUSE_MEMOk__BackingField {
            get {
                return this.CAUSE_MEMOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CAUSE_MEMOk__BackingFieldField, value) != true)) {
                    this.CAUSE_MEMOk__BackingFieldField = value;
                    this.RaisePropertyChanged("CAUSE_MEMOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CAUSE>k__BackingField", IsRequired=true)]
        public string CAUSEk__BackingField {
            get {
                return this.CAUSEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CAUSEk__BackingFieldField, value) != true)) {
                    this.CAUSEk__BackingFieldField = value;
                    this.RaisePropertyChanged("CAUSEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DC_CODE>k__BackingField", IsRequired=true)]
        public string DC_CODEk__BackingField {
            get {
                return this.DC_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DC_CODEk__BackingFieldField, value) != true)) {
                    this.DC_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("DC_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ENTER_DATE_FORMAT>k__BackingField", IsRequired=true)]
        public string ENTER_DATE_FORMATk__BackingField {
            get {
                return this.ENTER_DATE_FORMATk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ENTER_DATE_FORMATk__BackingFieldField, value) != true)) {
                    this.ENTER_DATE_FORMATk__BackingFieldField = value;
                    this.RaisePropertyChanged("ENTER_DATE_FORMATk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ENTER_DATE>k__BackingField", IsRequired=true)]
        public string ENTER_DATEk__BackingField {
            get {
                return this.ENTER_DATEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ENTER_DATEk__BackingFieldField, value) != true)) {
                    this.ENTER_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("ENTER_DATEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FailMessage>k__BackingField", IsRequired=true)]
        public string FailMessagek__BackingField {
            get {
                return this.FailMessagek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FailMessagek__BackingFieldField, value) != true)) {
                    this.FailMessagek__BackingFieldField = value;
                    this.RaisePropertyChanged("FailMessagek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ITEM_CODE>k__BackingField", IsRequired=true)]
        public string ITEM_CODEk__BackingField {
            get {
                return this.ITEM_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_CODEk__BackingFieldField, value) != true)) {
                    this.ITEM_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("ITEM_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LOC_CODE>k__BackingField", IsRequired=true)]
        public string LOC_CODEk__BackingField {
            get {
                return this.LOC_CODEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LOC_CODEk__BackingFieldField, value) != true)) {
                    this.LOC_CODEk__BackingFieldField = value;
                    this.RaisePropertyChanged("LOC_CODEk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MAKE_NO>k__BackingField", IsRequired=true)]
        public string MAKE_NOk__BackingField {
            get {
                return this.MAKE_NOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.MAKE_NOk__BackingFieldField, value) != true)) {
                    this.MAKE_NOk__BackingFieldField = value;
                    this.RaisePropertyChanged("MAKE_NOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ROWNUM>k__BackingField", IsRequired=true)]
        public decimal ROWNUMk__BackingField {
            get {
                return this.ROWNUMk__BackingFieldField;
            }
            set {
                if ((this.ROWNUMk__BackingFieldField.Equals(value) != true)) {
                    this.ROWNUMk__BackingFieldField = value;
                    this.RaisePropertyChanged("ROWNUMk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SERIAL_NO>k__BackingField", IsRequired=true)]
        public string SERIAL_NOk__BackingField {
            get {
                return this.SERIAL_NOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SERIAL_NOk__BackingFieldField, value) != true)) {
                    this.SERIAL_NOk__BackingFieldField = value;
                    this.RaisePropertyChanged("SERIAL_NOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<VALID_DATE_FORMAT>k__BackingField", IsRequired=true)]
        public string VALID_DATE_FORMATk__BackingField {
            get {
                return this.VALID_DATE_FORMATk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.VALID_DATE_FORMATk__BackingFieldField, value) != true)) {
                    this.VALID_DATE_FORMATk__BackingFieldField = value;
                    this.RaisePropertyChanged("VALID_DATE_FORMATk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<VALID_DATE>k__BackingField", IsRequired=true)]
        public string VALID_DATEk__BackingField {
            get {
                return this.VALID_DATEk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.VALID_DATEk__BackingFieldField, value) != true)) {
                    this.VALID_DATEk__BackingFieldField = value;
                    this.RaisePropertyChanged("VALID_DATEk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportF1913DataResult", Namespace="http://schemas.datacontract.org/2004/07/Wms3pl.Datas.Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class ImportF1913DataResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wms3pl.WpfClient.ExDataServices.P20WcfService.F1913DataImport[] F1913DataFailItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wms3pl.WpfClient.ExDataServices.P20WcfService.F1913Data[] F1913DataItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wms3pl.WpfClient.ExDataServices.P20WcfService.ExecuteResult ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wms3pl.WpfClient.ExDataServices.P20WcfService.F1913DataImport[] F1913DataFailItems {
            get {
                return this.F1913DataFailItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.F1913DataFailItemsField, value) != true)) {
                    this.F1913DataFailItemsField = value;
                    this.RaisePropertyChanged("F1913DataFailItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wms3pl.WpfClient.ExDataServices.P20WcfService.F1913Data[] F1913DataItems {
            get {
                return this.F1913DataItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.F1913DataItemsField, value) != true)) {
                    this.F1913DataItemsField = value;
                    this.RaisePropertyChanged("F1913DataItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wms3pl.WpfClient.ExDataServices.P20WcfService.ExecuteResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="P20WcfService.P20WcfService")]
    public interface P20WcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P20WcfService/GetF1929WithF1909Tests", ReplyAction="http://tempuri.org/P20WcfService/GetF1929WithF1909TestsResponse")]
        Wms3pl.WpfClient.ExDataServices.P20WcfService.ExecuteResult[] GetF1929WithF1909Tests(string gupCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P20WcfService/GetF1929WithF1909Tests", ReplyAction="http://tempuri.org/P20WcfService/GetF1929WithF1909TestsResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P20WcfService.ExecuteResult[]> GetF1929WithF1909TestsAsync(string gupCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P20WcfService/InsertP200101ByAdjustType0", ReplyAction="http://tempuri.org/P20WcfService/InsertP200101ByAdjustType0Response")]
        Wms3pl.WpfClient.ExDataServices.P20WcfService.ExecuteResult InsertP200101ByAdjustType0(Wms3pl.WpfClient.ExDataServices.P20WcfService.F050301Data[] f050301Datas, string workType, string allId, string allTime, string address, string newDcCode, string cause, string causeMemo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P20WcfService/InsertP200101ByAdjustType0", ReplyAction="http://tempuri.org/P20WcfService/InsertP200101ByAdjustType0Response")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P20WcfService.ExecuteResult> InsertP200101ByAdjustType0Async(Wms3pl.WpfClient.ExDataServices.P20WcfService.F050301Data[] f050301Datas, string workType, string allId, string allTime, string address, string newDcCode, string cause, string causeMemo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P20WcfService/InsertP200101ByAdjustType1", ReplyAction="http://tempuri.org/P20WcfService/InsertP200101ByAdjustType1Response")]
        Wms3pl.WpfClient.ExDataServices.P20WcfService.ExecuteResult InsertP200101ByAdjustType1(Wms3pl.WpfClient.ExDataServices.P20WcfService.F1913Data[] f1913Datas, System.Collections.Generic.KeyValuePair<int, Wms3pl.WpfClient.ExDataServices.P20WcfService.SerialNoResult[]>[] serialNoResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P20WcfService/InsertP200101ByAdjustType1", ReplyAction="http://tempuri.org/P20WcfService/InsertP200101ByAdjustType1Response")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P20WcfService.ExecuteResult> InsertP200101ByAdjustType1Async(Wms3pl.WpfClient.ExDataServices.P20WcfService.F1913Data[] f1913Datas, System.Collections.Generic.KeyValuePair<int, Wms3pl.WpfClient.ExDataServices.P20WcfService.SerialNoResult[]>[] serialNoResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P20WcfService/ImportF1913DataItems", ReplyAction="http://tempuri.org/P20WcfService/ImportF1913DataItemsResponse")]
        Wms3pl.WpfClient.ExDataServices.P20WcfService.ImportF1913DataResult ImportF1913DataItems(string dcCode, string gupCode, string custCode, Wms3pl.WpfClient.ExDataServices.P20WcfService.F1913DataImport[] importF1913Datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/P20WcfService/ImportF1913DataItems", ReplyAction="http://tempuri.org/P20WcfService/ImportF1913DataItemsResponse")]
        System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P20WcfService.ImportF1913DataResult> ImportF1913DataItemsAsync(string dcCode, string gupCode, string custCode, Wms3pl.WpfClient.ExDataServices.P20WcfService.F1913DataImport[] importF1913Datas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface P20WcfServiceChannel : Wms3pl.WpfClient.ExDataServices.P20WcfService.P20WcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class P20WcfServiceClient : System.ServiceModel.ClientBase<Wms3pl.WpfClient.ExDataServices.P20WcfService.P20WcfService>, Wms3pl.WpfClient.ExDataServices.P20WcfService.P20WcfService {
        
        public P20WcfServiceClient() {
        }
        
        public P20WcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public P20WcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public P20WcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public P20WcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wms3pl.WpfClient.ExDataServices.P20WcfService.ExecuteResult[] GetF1929WithF1909Tests(string gupCode) {
            return base.Channel.GetF1929WithF1909Tests(gupCode);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P20WcfService.ExecuteResult[]> GetF1929WithF1909TestsAsync(string gupCode) {
            return base.Channel.GetF1929WithF1909TestsAsync(gupCode);
        }
        
        public Wms3pl.WpfClient.ExDataServices.P20WcfService.ExecuteResult InsertP200101ByAdjustType0(Wms3pl.WpfClient.ExDataServices.P20WcfService.F050301Data[] f050301Datas, string workType, string allId, string allTime, string address, string newDcCode, string cause, string causeMemo) {
            return base.Channel.InsertP200101ByAdjustType0(f050301Datas, workType, allId, allTime, address, newDcCode, cause, causeMemo);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P20WcfService.ExecuteResult> InsertP200101ByAdjustType0Async(Wms3pl.WpfClient.ExDataServices.P20WcfService.F050301Data[] f050301Datas, string workType, string allId, string allTime, string address, string newDcCode, string cause, string causeMemo) {
            return base.Channel.InsertP200101ByAdjustType0Async(f050301Datas, workType, allId, allTime, address, newDcCode, cause, causeMemo);
        }
        
        public Wms3pl.WpfClient.ExDataServices.P20WcfService.ExecuteResult InsertP200101ByAdjustType1(Wms3pl.WpfClient.ExDataServices.P20WcfService.F1913Data[] f1913Datas, System.Collections.Generic.KeyValuePair<int, Wms3pl.WpfClient.ExDataServices.P20WcfService.SerialNoResult[]>[] serialNoResults) {
            return base.Channel.InsertP200101ByAdjustType1(f1913Datas, serialNoResults);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P20WcfService.ExecuteResult> InsertP200101ByAdjustType1Async(Wms3pl.WpfClient.ExDataServices.P20WcfService.F1913Data[] f1913Datas, System.Collections.Generic.KeyValuePair<int, Wms3pl.WpfClient.ExDataServices.P20WcfService.SerialNoResult[]>[] serialNoResults) {
            return base.Channel.InsertP200101ByAdjustType1Async(f1913Datas, serialNoResults);
        }
        
        public Wms3pl.WpfClient.ExDataServices.P20WcfService.ImportF1913DataResult ImportF1913DataItems(string dcCode, string gupCode, string custCode, Wms3pl.WpfClient.ExDataServices.P20WcfService.F1913DataImport[] importF1913Datas) {
            return base.Channel.ImportF1913DataItems(dcCode, gupCode, custCode, importF1913Datas);
        }
        
        public System.Threading.Tasks.Task<Wms3pl.WpfClient.ExDataServices.P20WcfService.ImportF1913DataResult> ImportF1913DataItemsAsync(string dcCode, string gupCode, string custCode, Wms3pl.WpfClient.ExDataServices.P20WcfService.F1913DataImport[] importF1913Datas) {
            return base.Channel.ImportF1913DataItemsAsync(dcCode, gupCode, custCode, importF1913Datas);
        }
    }
}
