//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2020/9/4 下午 03:02:54
namespace Wms3pl.WpfClient.ExDataServices.SignalRExDataService
{
    
    /// <summary>
    /// There are no comments for SignalRExDataSource in the schema.
    /// </summary>
    public partial class SignalRExDataSource : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new SignalRExDataSource object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SignalRExDataSource(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Wms3pl.Datas.Shared.Entities", "Wms3pl.WpfClient.ExDataServices.SignalRExDataService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Wms3pl.WpfClient.ExDataServices.SignalRExDataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Wms3pl.Datas.Shared.Entities.", clientType.Name);
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for ExecuteResults in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ExecuteResult> ExecuteResults
        {
            get
            {
                if ((this._ExecuteResults == null))
                {
                    this._ExecuteResults = base.CreateQuery<ExecuteResult>("ExecuteResults");
                }
                return this._ExecuteResults;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ExecuteResult> _ExecuteResults;
        /// <summary>
        /// There are no comments for ExecuteResults in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToExecuteResults(ExecuteResult executeResult)
        {
            base.AddObject("ExecuteResults", executeResult);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"Wms3pl.Datas.Shared.Entities\" xmlns=\"http://schemas.microsoft.com/ado" +
                "/2006/04/edm\"><EntityType Name=\"ExecuteResult\"><Key><PropertyRef Name=\"IsSuccess" +
                "ed\" /></Key><Property Name=\"IsSuccessed\" Type=\"Edm.Boolean\" Nullable=\"false\" /><" +
                "Property Name=\"Message\" Type=\"Edm.String\" /><Property Name=\"No\" Type=\"Edm.String" +
                "\" /></EntityType><EntityType Name=\"CheckLoc\" BaseType=\"Wms3pl.Datas.Shared.Entit" +
                "ies.ExecuteResult\"><Property Name=\"DcCode\" Type=\"Edm.String\" /><Property Name=\"W" +
                "arehouseId\" Type=\"Edm.String\" /><Property Name=\"LocCode\" Type=\"Edm.String\" /><Pr" +
                "operty Name=\"LocType\" Type=\"Edm.String\" /></EntityType><EntityType Name=\"CheckLo" +
                "cItem\" BaseType=\"Wms3pl.Datas.Shared.Entities.CheckLoc\"><Property Name=\"ItemCode" +
                "\" Type=\"Edm.String\" /></EntityType></Schema><Schema Namespace=\"Wms3pl.WebService" +
                "s.SignalR\" xmlns=\"http://schemas.microsoft.com/ado/2006/04/edm\"><EntityContainer" +
                " Name=\"SignalRExDataSource\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"E" +
                "xecuteResults\" EntityType=\"Wms3pl.Datas.Shared.Entities.ExecuteResult\" /><Functi" +
                "onImport Name=\"CheckAccountHasUserLogin\" ReturnType=\"Collection(Wms3pl.Datas.Sha" +
                "red.Entities.ExecuteResult)\" EntitySet=\"ExecuteResults\" m:HttpMethod=\"GET\"><Para" +
                "meter Name=\"userName\" Type=\"Edm.String\" /></FunctionImport></EntityContainer></S" +
                "chema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for Wms3pl.Datas.Shared.Entities.ExecuteResult in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IsSuccessed
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ExecuteResults")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("IsSuccessed")]
    public partial class ExecuteResult : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ExecuteResult object.
        /// </summary>
        /// <param name="isSuccessed">Initial value of IsSuccessed.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ExecuteResult CreateExecuteResult(bool isSuccessed)
        {
            ExecuteResult executeResult = new ExecuteResult();
            executeResult.IsSuccessed = isSuccessed;
            return executeResult;
        }
        /// <summary>
        /// There are no comments for Property IsSuccessed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsSuccessed
        {
            get
            {
                return this._IsSuccessed;
            }
            set
            {
                this.OnIsSuccessedChanging(value);
                this._IsSuccessed = value;
                this.OnIsSuccessedChanged();
                this.OnPropertyChanged("IsSuccessed");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsSuccessed;
        partial void OnIsSuccessedChanging(bool value);
        partial void OnIsSuccessedChanged();
        /// <summary>
        /// There are no comments for Property Message in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Message
        {
            get
            {
                return this._Message;
            }
            set
            {
                this.OnMessageChanging(value);
                this._Message = value;
                this.OnMessageChanged();
                this.OnPropertyChanged("Message");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Message;
        partial void OnMessageChanging(string value);
        partial void OnMessageChanged();
        /// <summary>
        /// There are no comments for Property No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string No
        {
            get
            {
                return this._No;
            }
            set
            {
                this.OnNoChanging(value);
                this._No = value;
                this.OnNoChanged();
                this.OnPropertyChanged("No");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _No;
        partial void OnNoChanging(string value);
        partial void OnNoChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Wms3pl.Datas.Shared.Entities.CheckLoc in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IsSuccessed
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("IsSuccessed")]
    public partial class CheckLoc : ExecuteResult
    {
        /// <summary>
        /// Create a new CheckLoc object.
        /// </summary>
        /// <param name="isSuccessed">Initial value of IsSuccessed.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CheckLoc CreateCheckLoc(bool isSuccessed)
        {
            CheckLoc checkLoc = new CheckLoc();
            checkLoc.IsSuccessed = isSuccessed;
            return checkLoc;
        }
        /// <summary>
        /// There are no comments for Property DcCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DcCode
        {
            get
            {
                return this._DcCode;
            }
            set
            {
                this.OnDcCodeChanging(value);
                this._DcCode = value;
                this.OnDcCodeChanged();
                this.OnPropertyChanged("DcCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DcCode;
        partial void OnDcCodeChanging(string value);
        partial void OnDcCodeChanged();
        /// <summary>
        /// There are no comments for Property WarehouseId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string WarehouseId
        {
            get
            {
                return this._WarehouseId;
            }
            set
            {
                this.OnWarehouseIdChanging(value);
                this._WarehouseId = value;
                this.OnWarehouseIdChanged();
                this.OnPropertyChanged("WarehouseId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _WarehouseId;
        partial void OnWarehouseIdChanging(string value);
        partial void OnWarehouseIdChanged();
        /// <summary>
        /// There are no comments for Property LocCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LocCode
        {
            get
            {
                return this._LocCode;
            }
            set
            {
                this.OnLocCodeChanging(value);
                this._LocCode = value;
                this.OnLocCodeChanged();
                this.OnPropertyChanged("LocCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LocCode;
        partial void OnLocCodeChanging(string value);
        partial void OnLocCodeChanged();
        /// <summary>
        /// There are no comments for Property LocType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LocType
        {
            get
            {
                return this._LocType;
            }
            set
            {
                this.OnLocTypeChanging(value);
                this._LocType = value;
                this.OnLocTypeChanged();
                this.OnPropertyChanged("LocType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LocType;
        partial void OnLocTypeChanging(string value);
        partial void OnLocTypeChanged();
    }
    /// <summary>
    /// There are no comments for Wms3pl.Datas.Shared.Entities.CheckLocItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IsSuccessed
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("IsSuccessed")]
    public partial class CheckLocItem : CheckLoc
    {
        /// <summary>
        /// Create a new CheckLocItem object.
        /// </summary>
        /// <param name="isSuccessed">Initial value of IsSuccessed.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CheckLocItem CreateCheckLocItem(bool isSuccessed)
        {
            CheckLocItem checkLocItem = new CheckLocItem();
            checkLocItem.IsSuccessed = isSuccessed;
            return checkLocItem;
        }
        /// <summary>
        /// There are no comments for Property ItemCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ItemCode
        {
            get
            {
                return this._ItemCode;
            }
            set
            {
                this.OnItemCodeChanging(value);
                this._ItemCode = value;
                this.OnItemCodeChanged();
                this.OnPropertyChanged("ItemCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ItemCode;
        partial void OnItemCodeChanging(string value);
        partial void OnItemCodeChanged();
    }
}
